"""Centralized UI strings to avoid hardcoded literals in code.

STRINGS_EL/STRINGS_EN are nested dicts grouping labels, button texts, popup
titles, and common messages. Keys are organized by category to make navigation
easier. When adding new strings, place them under the most appropriate category.
"""

STRINGS_EL = {
    "BUTTONS": {
        "ADD": "Προσθήκη",
        "ADD_MAINTENANCE": "+ Προσθήκη Νέας Συντήρησης",
        "ADD_MODEL": "+ Προσθήκη Νέου Μοντέλου",
        "APPLY": "Εφαρμογή",
        "BACK": "Πίσω",
        "BACKUP_APPLY": "Backup & Εφαρμογή",
        "BROWSE_FILE": "Επιλογή αρχείου",
        "CANCEL": "Ακύρωση",
        "CLOSE": "Κλείσιμο",
        "CONFIRM": "Επιβεβαίωση",
        "CONTINUE": "Συνέχεια",
        "COPY": "Αντιγραφή",
        "DELETE": "Διαγραφή",
        "EDIT": "Επεξεργασία",
        "EMAIL": "Email",
        "IMPORT": "Εισαγωγή",
        "INSPECT": "Επιθεώρηση",
        "INSPECTIONS": "Επιθεωρήσεις",
        "LIST": "Λίστα",
        "LOGIN": "Σύνδεση",
        "LOGOUT": "Αποσύνδεση",
        "MAINTENANCE": "Συντήρηση",
        "NO": "Όχι",
        "OK": "ΟΚ",
        "OPEN": "Άνοιγμα",
        "REFRESH": "Ανανέωση",
        "REPLACE": "Αντικατάσταση",
        "REPLACE_ALL": "Αντικατάσταση Όλων",
        "RESET": "Επαναφορά",
        "SYNC_NOW": "Συγχρονισμός τώρα",
        "SAVE": "Αποθήκευση",
        "SETTINGS": "Ρυθμίσεις",
        "SKIP": "Παράλειψη",
        "SKIP_FOR_NOW": "Παράλειψη προς το παρόν",
        "SKIP_ALL": "Παράλειψη Όλων",
        "UPDATE": "Ενημέρωση",
        "VIEW": "Προβολή",
        "YES": "Ναι",
    },
    "MESSAGES": {
        "ACTIVE_LABEL": "Ενεργός",
        "ADD_ELEMENTS_PROMPT": "Προσθέστε στοιχεία για τον νέο υποσταθμό πριν τη συνέχεια:",
        "ADD_ELEMENTS_TITLE": "Προσθήκη στοιχείων",
        "ADD_ELEMENT_BEFORE_CONTINUE": "Προσθέστε τουλάχιστον ένα στοιχείο πριν συνεχίσετε.",
        "ADD_ELEMENT_BTN": "Προσθήκη Νέου Στοιχείου",
        "ADD_ELEMENT_TITLE": "Προσθήκη Στοιχείου",
        "ADD_MANUAL": "Προσθήκη Manual",
        "ADD_MENU_TITLE": "Προσθήκη υποσταθμών και στοιχείων",
        "ADD_MODEL_TITLE": "Προσθήκη Νέου Μοντέλου",
        "ADD_NEW_SUBSTATION_PROMPT": "Ή προσθέστε νέο υποσταθμό:",
        "ADD_SUBSTATION_BTN": "Προσθήκη Νέου Υποσταθμού",
        "ADD_SUBSTATION_TITLE": "Προσθήκη Υποσταθμού",
        "ADOPTION": "Ανάληψη",
        "ADOPTION_DATE_LABEL": "Ημερομηνία Υιοθέτησης:",
        "ALL_LABEL": "(Όλα)",
        "ALL_SUBSTATIONS_LABEL": "Όλοι οι Υ/Σ",
        "ANDROID_FILECHOOSER_FALLBACK": "Ο επιλογέας αρχείων του Android δεν είναι διαθέσιμος. Χρησιμοποίησε τη λίστα αρχείων στο παράθυρο.",
        "APP_INFO_BODY": "HEDNO Substations DEDD/KSMTH/TEI\nVersion: {version}\nDB Version: {db_version}\nCompatibility: {compat_status}\n\nApplication features:\n• View and manage substation database\n• Add/edit/delete substations and elements\n• Circuit breaker categories (SF6/Oil/Low Oil)\n• Manage element types (models/manufacturers/cycles)\n• Maintenance records\n• Import maintenance from e-mail (.eml)\n• Maintenance history (all/by substation)\n• Breaker measurements (insulation/passage/operations)\n• SF6 gas quality & leaks (kg)\n• SF6 management (leakage report by year)\n• Export SF6 Excel reports (summary & per substation)\n• Print maintenance PDF reports\n• Inspections (entry/view/history)\n• Isolation requests\n• Import substations/elements from CSV/Excel\n• PDF & Excel reports\n\nApp folder: {app_dir}",
        "APP_INFO_SHORT": "Πληρ. Εφαρμ.",
        "APP_INFO_TITLE": "Πληροφορίες Εφαρμογής",
        "APP_TITLE": "Υποσταθμοί ΔΕΔΔΗΕ ΔΕΕΔ/ΚΣΜΘ/ΤΕΙ",
        "BREAKER_CATEGORIES_ALL": [
            "SF6",
            "Πτωχού Ελαίου",
            "Ελαίου",
            "Κενού",
        ],
        "BREAKER_CATEGORIES_HV": ["SF6", "Ελαίου"],
        "BREAKER_CATEGORIES_MV": [
            "SF6",
            "Πτωχού Ελαίου",
            "Ελαίου",
            "Κενού",
        ],
        "BREAKER_CATEGORY_LABEL": "Κατηγορία Διακόπτη:",
        "BREAKER_LABEL_CAPACITOR": "Διακόπτης Πυκνωτών",
        "BREAKER_LABEL_CENTRAL": "Κεντρικός",
        "BREAKER_LABEL_INTERCON": "Διασυνδετικός",
        "BREAKER_LABEL_LINE": "Γραμμής",
        "BREAKER_TYPES": [
            "Κεντρικός",
            "Γραμμής",
            "Διασυνδετικός",
            "Διακόπτης Πυκνωτών",
        ],
        "BREAKER_TYPE_LABEL": "Τύπος Διακόπτη:",
        "CAPACITORS": "Πυκνωτές",
        "CHANGELOG_BUTTON": "Change-log",
        "CHANGELOG_FILE_LABEL": "Διαδρομή αρχείου change log (.jsonl/.txt):",
        "CHANGELOG_RECORDED": "Η αλλαγή καταγράφηκε στο change log.",
        "CHANGES_SAVED": "Οι αλλαγές αποθηκεύτηκαν!",
        "COMMENTS_LABEL": "Σχόλια: {text}",
        "CONFIRM_DELETE_MAINT_FMT": "Είστε σίγουροι ότι θέλετε να διαγράψετε\nαυτή τη συντήρηση;",
        "CONFIRM_DELETE_PERSON_FMT": 'Είστε σίγουροι ότι θέλετε να διαγράψετε\nτο άτομο "{person_name}";',
        "CONFIRM_DELETE_SUBSTATION_FMT": 'Είστε σίγουροι ότι θέλετε να διαγράψετε\nτον υποσταθμό "{substation_name}"\nκαι ΟΛΑ τα στοιχεία του;',
        "CONFIRM_DELETE_TITLE": "Επιβεβαίωση Διαγραφής",
        "CONTINUE": "Συνέχεια",
        "COPY": "Copy",
        "COPYING_FILE": "Αντιγραφή αρχείου...",
        "COPYING_FILE_MSG": "Αντιγραφή αρχείου από το σύστημα αρχείων. Παρακαλώ περιμένετε...",
        "COPY_PATH": "Αντιγραφή διαδρομής",
        "CREW_LABEL": "Συνεργείο Συντήρησης (προαιρετικό):",
        "DASH": "-",
        "DATE_HINT": "YYYY-MM-DD",
        "DATE_LABEL": "Ημερομηνία:",
        "DATE_PLAIN": "Ημερομηνία",
        "DATE_PREFIX": "Ημερομηνία:",
        "DATE_REQUIRED": "Η ημερομηνία είναι υποχρεωτική!",
        "DATE_TIME_LABEL": "Ημερομηνία & Ώρα:",
        "DAYS": [
            "Δευτέρα",
            "Τρίτη",
            "Τετάρτη",
            "Πέμπτη",
            "Παρασκευή",
            "Σάββατο",
            "Κυριακή",
        ],
        "DAY_LABEL": "Ημέρα:",
        "DB_FILE_INVALID": "Μη έγκυρο αρχείο βάσης δεδομένων!",
        "DB_FILE_NOT_FOUND": "Το αρχείο της βάσης δεδομένων δεν βρέθηκε!",
        "DB_PATH_BUTTON": "Αλλαγή",
        "DB_PATH_DEFAULT": "(Προεπιλεγμένη)",
        "DB_PATH_LABEL": "Διαδρομή Βάσης Δεδομένων:",
        "DB_PATH_SAVED_RESTART": "Η διαδρομή της βάσης δεδομένων αποθηκεύτηκε. Η εφαρμογή θα επανεκκινήσει τώρα.",
        "DB_PATH_SELECT": "Επιλέξτε αρχείο βάσης δεδομένων",
        "SYNC_SETTINGS_LABEL": "Ρυθμίσεις Συγχρονισμού / Αντιγράφων:",
        "SYNC_SETTINGS_HELP_BUTTON": "Βοήθεια Sync Settings",
        "SYNC_SETTINGS_HELP_TEXT": "Συγχρονισμός με OneDrive (πολλοί χρήστες):\n1) Ο Χρήστης Α δημιουργεί κοινόχρηστο φάκελο OneDrive και τον μοιράζεται με την ομάδα.\n2) Κάθε χρήστης συγχρονίζει αυτόν τον φάκελο τοπικά (OneDrive Desktop).\n3) Ορίστε sync_root_path στην ΤΟΠΙΚΗ διαδρομή του OneDrive (π.χ. C:\\Users\\...\\OneDrive\\Κοινόχρηστος).\n4) Μπορείτε να χρησιμοποιήσετε υπάρχοντα φάκελο - δεν χρειάζεται να δημιουργήσετε νέο.\n5) Το OneDrive αυτόματα συγχρονίζει αλλαγές μεταξύ όλων των χρηστών στο παρασκήνιο.\n6) Η εφαρμογή δημιουργεί τους απαραίτητους υποφακέλους αυτόματα.",
        "SYNC_AUTO_ENABLED_LABEL": "Αυτόματος συγχρονισμός:",
        "STARTUP_SYNC_PROBE_ENABLED_LABEL": "Έλεγχος διαφορών στην εκκίνηση (startup probe):",
        "STARTUP_SYNC_PROMPT_ON_CHANGE_LABEL": "Ερώτηση πριν τον συγχρονισμό όταν υπάρχουν διαφορές:",
        "STARTUP_SYNC_CHANGES_TITLE": "Τι άλλαξε από την τελευταία εκκίνηση:",
        "SYNC_INTERVAL_MINUTES_LABEL": "Διάστημα αυτόματου συγχρονισμού (λεπτά):",
        "SYNC_BACKUP_ON_CHANGE_LABEL": "Snapshot όταν υπάρχουν νέες αποδεκτές αλλαγές:",
        "SYNC_HOT_KEEP_LABEL": "Πλήθος snapshots hot backup:",
        "SYNC_RETENTION_ENABLED_LABEL": "Αυτόματη διαγραφή παλιών αρχείων sync:",
        "SYNC_RETENTION_DAYS_LABEL": "Διατήρηση αρχείων sync (ημέρες):",
        "SYNC_RETENTION_DAYS_INVALID": "Μη έγκυρη τιμή για ημέρες διατήρησης sync.",
        "SYNC_ROOT_PATH_LABEL": "Φάκελος sync_root_path:",
        "SYNC_ROOT_PATH_HINT": "Κενό = προεπιλογή (δίπλα στη βάση: sync_exchange)",
        "BACKUP_ROOT_PATH_LABEL": "Φάκελος backup_root_path:",
        "BACKUP_ROOT_PATH_HINT": "Κενό = προεπιλογή (δίπλα στη βάση: backups_auto)",
        "SYNC_INTERVAL_INVALID": "Μη έγκυρη τιμή για λεπτά συγχρονισμού.",
        "SYNC_HOT_KEEP_INVALID": "Μη έγκυρη τιμή για πλήθος snapshots.",
        "SYNC_MANUAL_SUMMARY_FMT": "Επεξεργασία εισερχομένων ολοκληρώθηκε.\nΕπεξεργασμένα: {processed}\nΑποδεκτά: {accepted}\nΣε σύγκρουση: {conflicts}\nΑπορριφθέντα: {rejected}",
        "SYNC_SNAPSHOT_LINE_FMT": "Snapshot: {snapshot}",
        "SYNC_AUTO_SUMMARY": "Αυτόματος συγχρονισμός ολοκληρώθηκε:\n✓ Αποδεκτά: {accepted}\n⚠ Συγκρούσεις: {conflicts}\n❌ Απορριφθέντα: {rejected}",
        "SYNC_BACKUP_CREATED": "Δημιουργήθηκε αντίγραφο ασφαλείας.",
        "SYNC_ISSUES_FOUND": "Βρέθηκαν προηγούμενες αλλαγές με προβλήματα:\n• Απορριφθέντα: {rejected}\n• Συγκρούσεις: {conflicts}",
        "SYNC_ISSUES_ACTION": "Ελέγξτε τους φακέλους rejected και conflicts στο sync_root.",
        "SYNC_ONEDRIVE_BUTTON": "Συγχρονισμός OneDrive",
        "IMPORT_SYNC_INBOX_BUTTON": "Συγχρονισμός με OneDrive",
        "CHANGES_EXPORTED_FMT": "Εξήχθησαν {count} αλλαγές στο αρχείο:\n{file}",
        "SYNC_EXPORTED_CHANGES_LINE_FMT": "Εξερχόμενες αλλαγές: {count} (αρχείο: {file})",
        "CHANGES_EXPORT_ERROR": "Σφάλμα κατά την εξαγωγή αλλαγών: ",
        "EXPORT_CHANGES_BUTTON": "Εξαγωγή Αλλαγών Τώρα",
        "EXPORT_CHANGES_ERROR_FMT": "Σφάλμα εξαγωγής: {error}",
        "NO_PENDING_CHANGES": "Δεν υπάρχουν αλλαγές προς εξαγωγή.",
        "SYNC_BUTTON": "Συγχρ/σμός",
        "SYNCING": "Συγχρονισμός...",
        "SYNC_ERROR": "Σφάλμα κατά τον συγχρονισμό",
        "SETTINGS_SAVED": "Ρυθμίσεις αποθηκεύτηκαν",
        "NO_DB": "Δεν φορτώθηκε βάση δεδομένων",
        "DIVISION_DEFAULT": "ΤΜΘ",
        "DIVISION_LABEL": "Τμήμα",
        "DUPLICATE_OPTIONS_INCOMPLETE": "Ολοκληρώστε τις επιλογές για όλα τα διπλότυπα ή χρησιμοποιήστε 'Αντικατάσταση Όλων' / 'Παράλειψη Όλων'.",
        "EDIT_PERSON_TITLE": "Επεξεργασία Ατόμου",
        "ELEMENTS_LIST_LABEL": "Στοιχεία που συντηρήθηκαν:",
        "ELEMENTS_SECTION_LABEL": "Στοιχεία που συντηρήθηκαν (τουλάχιστον 1):",
        "ELEMENT_ADDED": "Το στοιχείο προστέθηκε στον {substation_name}!",
        "ELEMENT_BREAKER_MT": "Διακόπτης ΜΤ",
        "ELEMENT_BREAKER_SUBSTR": "Διακόπτης",
        "ELEMENT_BREAKER_YT": "Διακόπτης ΥΤ",
        "ELEMENT_COMMENTS_LABEL": "Σχόλια Στοιχείου:",
        "ELEMENT_COMMENTS_SECTION": "Σχόλια Στοιχείου",
        "ELEMENT_DUPLICATE": "Ένα στοιχείο με αυτό το όνομα υπάρχει ήδη σε αυτόν τον υποσταθμό!",
        "ELEMENT_LABEL": "Στοιχείο",
        "ELEMENT_MAINT_HISTORY_TITLE": "Ιστορικό Συντηρήσεων Στοιχείου - {element_name}",
        "ELEMENT_MANUFACTURE_YEAR_HINT": "YYYY",
        "ELEMENT_MANUFACTURE_YEAR_LABEL": "Έτος κατασκευής",
        "ELEMENT_NAME_HINT": "Όνομα Στοιχείου",
        "ELEMENT_NAME_LABEL": "Όνομα Στοιχείου",
        "ELEMENT_TYPES": [
            "Διακόπτης ΥΤ",
            "Διακόπτης ΜΤ",
            "Μετασχηματιστής 150/20KV",
            "Motor Drive",
            "Μ/Σ Έγχυσης",
            "Μ/Σ Έντασης",
            "Μ/Σ Τάσης",
            "Μ/Σ ΧΤ/ΜΤ (ΒΜΣ)",
            "Αποζεύκτης",
            "Ασφαλειοαποζεύκτης",
            "Γειωτής",
            "Συστοιχία Πυκνωτών",
            "Αντίσταση Κόμβου",
            "Αλεξικέραυνο",
            "Συστοιχία Συσσωρευτών",
        ],
        "ELEMENT_TYPE_LABEL": "Τύπος Στοιχείου:",
        "ELEM_COMMENTS_HINT": "Σχόλια για αυτό το στοιχείο...",
        "EMAIL_LABEL": "Email:",
        "EMAIL_RECIPIENTS_MISSING": "Δεν υπάρχουν παραλήπτες email. Προσθέστε παραλήπτες από τη Διαχείριση Προσωπικού.",
        "EMAIL_RECIPIENT_LABEL": "Παραλήπτες email αναφοράς",
        "EMPTY_DB": "Κενή βάση δεδομένων",
        "EMPTY_PLACEHOLDER": "(Κενό)",
        "END_BEFORE_START": "Η ημερομηνία λήξης πρέπει να είναι μετά την έναρξη!",
        "ENTER_PATH": "Εισάγετε μια διαδρομή ή επιλέξτε ένα αρχείο!",
        "ENTER_SUBSTATION_NAME": "Εισάγετε το όνομα του υποσταθμού!",
        "ERROR_DURING_CHECK_PREFIX": "Σφάλμα κατά τον έλεγχο: ",
        "ERROR_FMT": "Σφάλμα: {exc}",
        "EXCEL": "Excel",
        "EXCEL_CREATED": "Το Excel δημιουργήθηκε:\n{path}",
        "EXCEL_CREATE_FAILED": "Αποτυχία δημιουργίας Excel:\n{err}",
        "EXISTING_MODELS_DIFF_HEADER": "[b]Υπάρχοντα Μοντέλα με Διαφορετικά Δεδομένα:[/b]",
        "EXPORT_HISTORY_LIST_PDF": "Εξαγωγή λίστας σε PDF",
        "EXPORT_MAINTENANCE_PDF": "Εξαγωγή PDF",
        "FILECHOICE_CANCELLED": "Η επιλογή αρχείου απέτυχε ή ακυρώθηκε.",
        "FILECHOOSER_ANDROID_ONLY": "Ο επιλογέας αρχείων είναι διαθέσιμος μόνο σε Android.",
        "FILECHOOSER_INTERNAL_ERROR": "Εσωτερικό σφάλμα επιλογέα αρχείων.",
        "FILECHOOSER_NOT_AVAILABLE": "Ο επιλογέας αρχείων δεν είναι διαθέσιμος",
        "FILE_DIALOG_ALL_FILES": "Όλα τα αρχεία",
        "FILE_DIALOG_EXCEL_FILES": "Αρχεία Excel",
        "FILE_DIALOG_CSV_FILES": "Αρχεία CSV",
        "FILE_DIALOG_JSON_FILES": "Αρχεία JSON",
        "FILE_DIALOG_ANDROID_CHANGELOG_FILES": "Αρχεία change log Android",
        "FILE_DIALOG_SAVE_TITLE": "Αποθήκευση αρχείου",
        "FILE_DIALOG_SELECT_TITLE": "Επιλογή αρχείου",
        "FILE_HAS_NO_DATA": "Το αρχείο δεν περιέχει δεδομένα.",
        "FILE_NOT_FOUND": "Το αρχείο δεν βρέθηκε!",
        "FILE_PATH_HINT": "Διαδρομή αρχείου",
        "FILE_PATH_LABEL": "Διαδρομή αρχείου:",
        "FILTER_GATE": "Φίλτρο Πύλης:",
        "FILTER_SUBSTATION": "Φίλτρο Υποσταθμού:",
        "FILTER_TYPE": "Φίλτρο Τύπου:",
        "FORM_NUMBER": "Αρ. Δελτίου:",
        "FORM_NUMBER_HINT": "Αρ. Δελτίου",
        "GATES": "Πύλες",
        "GATE_LABEL": "Πύλη",
        "GATE_PREFIX": "ΠΥΛΗ",
        "GOOGLE_MAPS_LINK": "Google Maps Link",
        "IMPORT_BUTTON": "Εισαγωγή/Εξαγωγή δεδομένων",
        "IMPORT_MENU_PROMPT": "Επιλέξτε τι θέλετε να εισάγετε/εξάγετε:",
        "IMPORT_ELEMENTS_BUTTON": "Εισαγωγή Στοιχείων από Αρχείο",
        "IMPORT_EXPORT_DB_BUTTON": "Εξαγωγή ολόκληρης Βάσης (Excel)",
        "IMPORT_TEMPLATE_PROMPT": "Ή δημιουργήστε πρότυπο εισαγωγής:",
        "IMPORT_TEMPLATE_ELEMENTS_BUTTON": "Δημιουργία Template Εισαγωγής",
        "IMPORT_OR_SELECT_FROM_LIST": "Ή επιλέξτε από τη λίστα:",
        "IMPORT_FAILED": "Η εισαγωγή απέτυχε:",
        "IMPORT_INSPECTIONS_DIALOG": "Εισαγωγή επιθεωρήσεων από αρχείο",
        "IMPORT_INSPECTIONS_DONE": "Εισαγωγή ολοκληρώθηκε ({inserted} εγγραφές).",
        "IMPORT_INSPECTIONS_TITLE": "Εισαγωγή Επιθεωρήσεων",
        "IMPORT_SUCCESS": "Επιτυχής εισαγωγή!",
        "INACTIVE_ELEMENTS": "Ανενεργά στοιχεία ({count})",
        "INFO": "Στοιχεία",
        "INSPECTION_BASE_FIELDS": [
            "Υποσταθμός",
            "Αρ. Φόρμας",
            "Μήνας",
            "Όνομα Επιθεωρητή",
            "Περιοχή",
            "Ημέρα",
            "Έτος",
            "Ημερομηνία",
        ],
        "INSPECTION_BUTTON": "Επιθεωρήσεις",
        "INSPECTION_COUNT_FMT": "{count} εγγραφές επιθεώρησης",
        "INSPECTION_ROWS": [
            "Έλεγχος εξωτερικών και εσωτερικών θυρών του υποσταθμού",
            "Έλεγχος εσωτερικού κτιρίου (φωτισμός, κλιματισμός, κ.λπ.)",
            "Έλεγχος περιβάλλοντος χώρου (βλαστικότητα, δέντρα, φωτισμός, κ.λπ.)",
            "Γενική επιθεώρηση εξοπλισμού πυρασφάλειας",
            "Οπτικός έλεγχος διαρροής/στάθμης/θερμοκρασίας λαδιού, σιλικογέλης στο μετασχηματιστή",
            "Οπτικός έλεγχος διαρροής λαδιού ή πίεσης SF6 ή πίεσης αέρα στους διακόπτες ΥΤ & 20kV",
            "Έλεγχος λειτουργίας ανεμιστήρα μετασχηματιστή",
            "Οπτικός έλεγχος μετασχηματιστή έγχυσης, ΜΕ, ΜΤ, μετασχηματιστή υπηρεσίας, ουδέτερης αντίστασης (θερμοκρασία)",
            "Οπτικός έλεγχος μονωτήρων (ρύπανση, γρατζουνιές, κ.λπ.)",
            "Οπτικός έλεγχος ασφαλειών και πυκνωτών",
            "Έλεγχος σημάνσεων στα πάνελ μετασχηματιστή, ηλεκτροδότη 150kV & 20kV",
            "Λήψη φωτογραφίας όταν απαιτείται",
            "Οπτικός έλεγχος πυλών, διαζεύκτων και γενικών κατασκευών για φωλιές, σπασίματα, μονωτήρες, κλαδιά, καλώδια κ.λπ.",
            "Οπτικός έλεγχος πάνελ ηλεκτροδότη 20kV (συναγερμοί, ενδείξεις, θύρες) και έλεγχος θορύβου/ιονοποίησης",
            "Έλεγχος υγρασίας (υπόγειο, κανάλια καλωδίων), αφυγραντήρες, θερμαντήρες, φορητές πυροσβεστήρες",
            "Έλεγχος φορτιστή 110V με οπτικό έλεγχο και μέτρηση/καταγραφή τάσης/ρεύματος",
            "Έλεγχος διάσβεσης συνεχούς ρεύματος στο κύριο πάνελ DC",
            "Οπτικός έλεγχος διαρροών στα στοιχεία μπαταρίας",
            "Οπτικός έλεγχος γεννήτριών και γεφυρών τους στον 1ο πόλο κάθε γραμμής (σπάσιμο, μονωτήρες, κ.λπ.)",
            "Έλεγχος λειτουργίας ψηφιακού συστήματος (λειτουργίες, ενδείξεις, σημάνσεις)",
            "Τροφοδοσία PC",
            "Απόψεις και προτάσεις για καλύτερη λειτουργία εξοπλισμού και κτιρίου γενικά",
        ],
        "INSPECTION_SAVED": "Επιθεώρηση αποθηκεύτηκε!",
        "INSPECTION_SECTION_2": "[b]Έλεγχος Περιοχών Υποσταθμού[/b]",
        "INSPECTION_SECTION_3": "[b]Μετασχηματιστής 150/20kV & Διακόπτες ΥΤ/20kV[/b]",
        "INSPECTION_SECTION_3A": "[b]Εξωτερικές Πύλες 20 kV[/b]",
        "INSPECTION_SECTION_3B": "[b]Εξωτερικές Πύλες 20 kV[/b]",
        "INSPECTION_SECTION_4": "[b]Κτίριο Ελέγχου & Βοηθητικές Υπηρεσίες[/b]",
        "INSPECTION_SECTION_5": "[b]Διακόπτες Γραμμής[/b]",
        "INSPECTION_SECTION_6": "[b]PC Ελέγχου[/b]",
        "INSPECTION_SECTION_7": "[b]Απόψεις[/b]",
        "INSPECTOR_LABEL": "Ονομ. Επιθεωρητή:",
        "INSTALLATION_SPACE": ["Εσωτερικός", "Εξωτερικός"],
        "INSTALLATION_SPACE_LABEL": "Χώρος Εγκατ.",
        "INSULATION_HINT": "0.0",
        "INSULATION_LABEL_FA": "FA-FA",
        "INSULATION_LABEL_FA_GND": "FA-GEI",
        "INSULATION_LABEL_FB": "FB-FB",
        "INSULATION_LABEL_FB_GND": "FB-GEI",
        "INSULATION_LABEL_FC": "FC-FC",
        "INSULATION_LABEL_FC_GND": "FC-GEI",
        "INSULATION_MEASUREMENT_CLOSED_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ ΜΟΝΩΣΗΣ - ΔΙΑΚΟΠΤΗΣ ΚΛΕΙΣΤΟΣ (ΦΑ-ΓΕΙ):",
        "INSULATION_MEASUREMENT_OPEN_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ ΜΟΝΩΣΗΣ - ΔΙΑΚΟΠΤΗΣ ΑΝΟΙΧΤΟΣ (ΦΑ-ΦΑ):",
        "INSULATION_PASSAGE_MEASUREMENT_CLOSED_HEADER": "ΑΝΤΙΣΤΑΣΗ ΔΙΕΛΕΥΣΗΣ (uOhm) - ΔΙΑΚΟΠΤΗΣ ΚΛΕΙΣΤΟΣ:",
        "INSULATION_PASSAGE_TITLE": "Αντίσταση Διέλευσης (uOhm)",
        "INSULATION_RESISTANCE_CLOSED_TITLE": "Αντίσταση Μόνωσης - Διακόπτης Κλειστός (Γείωση)",
        "INSULATION_RESISTANCE_OPEN_TITLE": "Αντίσταση Μόνωσης - Διακόπτης Ανοιχτός (Φάση-Φάση)",
        "INVALID_DATE_FORMAT": "Μη έγκυρη μορφή ημερομηνίας! Χρησιμοποιήστε: YYYY-MM-DD HH:MM",
        "ISOLATION_BUTTON": "Αιτήσεις Απομόνωσης",
        "ITEM_DELETED": "Το στοιχείο διαγράφηκε!",
        "LANGUAGE_LABEL": "Γλώσσα:",
        "LANGUAGE_OPTION_EL": "Ελληνικά",
        "LANGUAGE_OPTION_EN": "Αγγλικά",
        "LANGUAGE_SAVED_RESTART": "Η γλώσσα αποθηκεύτηκε. Η εφαρμογή θα επανεκκινήσει τώρα.",
        "LAST": "Τελευταία",
        "LEAKAGE_LABEL": "Διαρροή (kg)",
        "LOADING": "Φόρτωση...",
        "LOADING_ELEMENTS": "Φόρτωση στοιχείων...",
        "LOAD_MORE": "Φόρτωση περισσότερων",
        "LOC": "Τοποθεσία",
        "LOCAL_DB_BUTTON": "Βάση Δεδομένων",
        "LOGGED_IN_AS_FMT": "Συνδεδεμένος ως: {name} ({role})",
        "LOGIN_PROMPT": "Επιλέξτε το όνομά σας για να συνδεθείτε:",
        "LOGIN_REQUIRED": "Πρέπει να συνδεθείτε για να χρησιμοποιήσετε την εφαρμογή.",
        "LOGIN_SUCCESS_FMT": "Καλωσορίσατε, {name}!",
        "LOGIN_TITLE": "Σύνδεση Χρήστη",
        "LOGOUT_CONFIRM": "Θέλετε να αποσυνδεθείτε;",
        "MAINTENANCES": "Συμβάντα/Μετρήσεις",
        "MAINTENANCE_BUTTON": "Συμβάντα/Μετρήσεις",
        "MAINTENANCE_COMMENTS_SECTION": "Σχόλια Συμβάντος/Μέτρησης",
        "MAINTENANCE_CREATED": "Η συντήρηση καταχωρήθηκε!",
        "MAINTENANCE_CYCLE_HINT": "Αριθμός",
        "MAINTENANCE_CYCLE_LABEL": "Κύκλος Συντ.",
        "MAINTENANCE_DATE_HINT": "YYYY-MM-DD",
        "MAINTENANCE_DATE_LABEL": "Ημ/νία:",
        "MAINTENANCE_DELETED": "Η συντήρηση διαγράφηκε!",
        "MAINTENANCE_HEADER": "{type}: {name}",
        "MAINTENANCE_NAME_FMT": "Υ/Σ {substation_name} - {date}",
        "MAINTENANCE_NOT_FOUND": "Η συντήρηση δεν βρέθηκε.",
        "MAINTENANCE_SAVED_CHANGELOG": "Η συντήρηση καταγράφηκε στο αρχείο αλλαγών.",
        "MAINTENANCE_TYPES": [
            "Επαναληπτική συντήρηση",
            "Βλάβη",
            "Φυσικοχημικές/Αεριοχρωματογραφία",
        ],
        "MAINTENANCE_TYPE_LABEL": "Τύπος:",
        "MAINTENANCE_UPDATED": "Η συντήρηση ενημερώθηκε!",
        "MAINT_HISTORY_LABEL": "Ιστορικό Συντηρήσεων",
        "UNDONE_MAINTENANCES_LABEL": "Εκκρεμείς Συντηρήσεις",
        "TASKS_LEFT_LABEL": "Εργασίες που απομένουν",
        "MARK_COMPLETE_LABEL": "Ολοκληρώθηκε",
        "MAINT_LAST_LABEL": "Τελευταία Συντήρηση: {date}",
        "DGA_LABEL": "Φυσικοχημικές/Αεριοχρωματογραφία",
        "DGA_NEW_MEASUREMENT_LABEL": "Νέα μέτρηση Φυσικοχημικών/Αεριοχρωματογραφίας",
        "DGA_ADD_MEASUREMENT_SHORT": "Νέα Μέτρηση",
        "DGA_MAINT_FORM_TITLE": "Καταχώρηση Μέτρησης DGA",
        "DGA_START_BUTTON": "Έναρξη DGA",
        "DGA_SELECT_TRANSFORMER_REQUIRED": "Παρακαλώ επιλέξτε ένα μετασχηματιστή",
        "DGA_MAINT_NAME_FMT": "DGA - {element_name} ({date})",
        "DGA_SUBSTATION_TITLE_FMT": "{dga_label} - {substation_name}",
        "DGA_NO_MEASUREMENTS_FOR_SUBSTATION": "Δεν υπάρχουν μετρήσεις DGA για αυτόν τον υποσταθμό",
        "DGA_MEASUREMENTS_COUNT_FMT": "{element_name} (S/N: {serial_number}) - {count} μετρήσεις",
        "DGA_MEASUREMENTS_FOR_FMT": "Μετρήσεις DGA για: {element_name}",
        "DGA_VIEW_HISTORY_BUTTON": "Προβολή Ιστορικού Μετρήσεων",
        "MEASUREMENTS_HISTORY_LABEL": "Ιστορικό Μετρήσεων",
        "MEASUREMENTS_HISTORY_BUTTON": "Ιστορικό Μετρήσεων",
        "ONLY_FAILED_LABEL": "Μόνο εκτός ορίων",
        "DGA_ELEMENT_NOT_FOUND": "Το στοιχείο δεν βρέθηκε.",
        "DGA_SUBSTATION_NOT_FOUND": "Δεν βρέθηκε ο υποσταθμός για την καταχώρηση DGA.",
        "DGA_RECORD_NOT_FOUND": "Δεν βρέθηκε η εγγραφή DGA.",
        "DGA_POPUP_TITLE_FMT": "DGA - {element_name}",
        "DGA_POPUP_EDIT_TITLE_FMT": "Επεξεργασία DGA - {element_name}",
        "DGA_SAVE_SUCCESS_FMT": "Η αναφορά DGA αποθηκεύτηκε:\n{path}",
        "DGA_SAVE_FAILED_FMT": "Αποτυχία αποθήκευσης DGA:\n{error}",
        "DGA_HISTORY_TITLE_FMT": "Ιστορικό DGA - {element_name}",
        "DGA_HISTORY_ROW_FMT": "Μέτρηση: {measurement_date} | Δειγματοληψία: {sampling_date} | Δημιουργία: {created_at}",
        "DGA_OPEN_REPORT_BUTTON": "Άνοιγμα Αναφοράς",
        "DGA_NO_MEASUREMENTS_FOR_ELEMENT": "Δεν βρέθηκαν μετρήσεις DGA για αυτό το στοιχείο.",
        "DGA_SAMPLING_DATE_LABEL": "Ημερομηνία Δειγματοληψίας",
        "DGA_MEASUREMENT_DATE_LABEL": "Ημερομηνία Μέτρησης",
        "DGA_SAMPLE_POINT_LABEL": "Σημείο Δειγματοληψίας",
        "DGA_METHOD_LABEL": "Μέθοδος",
        "DGA_SAMPLING_RESPONSIBLE_LABEL": "Υπεύθυνος Δειγματοληψίας",
        "DGA_MEASUREMENT_RESPONSIBLE_LABEL": "Υπεύθυνος Μέτρησης",
        "DGA_SAMPLE_TEMPERATURE_LABEL": "Θερμοκρασία Δείγματος",
        "DGA_DENSITY_LABEL": "Πυκνότητα",
        "DGA_HUMIDITY_LABEL": "Υγρασία",
        "DGA_DIELECTRIC_STRENGTH_LABEL": "Διηλεκτρική Αντοχή",
        "DGA_LOSS_FACTOR_LABEL": "Συντελεστής Απωλειών",
        "DGA_SURFACE_TENSION_LABEL": "Διεπιφανειακή Τάση",
        "DGA_NOTES_LABEL": "Παρατηρήσεις",
        "DGA_BADGE_BAD": "ΕΚΤΟΣ ΟΡΙΩΝ",
        "DGA_BADGE_WARN": "ΑΝΕΚΤΟ / WARNING",
        "DGA_BADGE_OK": "OK",
        "DGA_LEGEND_TITLE": "Υπόμνημα",
        "DGA_LEGEND_OK_COLOR": "Πράσινο=OK",
        "DGA_LEGEND_WARN_COLOR": "Κίτρινο=ΑΝΕΚΤΟ/Warning",
        "DGA_LEGEND_BAD_COLOR": "Κόκκινο=ΕΚΤΟΣ ΟΡΙΩΝ",
        "DGA_LIMIT_FMT": "όριο: {limit}",
        "DGA_GOOD_TOLERABLE_FMT": "καλό: {good} | ανεκτό: {tolerable}",
        "DGA_MORE_FMT": "+{remaining} ακόμη",
        "DGA_PROBLEMATIC_TITLE": "DGA Προειδοποιήσεις / Εκτός Ορίων",
        "DGA_NO_PROBLEMATIC": "Δεν βρέθηκαν DGA μετρήσεις με warning ή εκτός ορίων.",
        "DGA_PROBLEMATIC_COUNT_FMT": "Βρέθηκαν {count} μετρήσεις με warning/εκτός ορίων.",
        "DGA_MEAS_DATE_LABEL": "Ημ. μέτρησης",
        "DGA_STATUS_BAD_MSG": "Κατάσταση ορίων: ΕΚΤΟΣ ΟΡΙΩΝ (ΚΟΚΚΙΝΟ)",
        "DGA_STATUS_WARN_MSG": "Κατάσταση ορίων: ΑΝΕΚΤΟ / WARNING (ΚΙΤΡΙΝΟ)",
        "DGA_STATUS_OK_MSG": "Κατάσταση ορίων: OK (ΠΡΑΣΙΝΟ)",
        "DGA_SECTION_META_LABEL": "Στοιχεία Δειγματοληψίας / Μέτρησης",
        "DGA_SECTION_GASES_LABEL": "Αέρια",
        "DGA_SECTION_PHYSCHEM_LABEL": "Φυσικοχημικές Μετρήσεις",
        "DGA_SECTION_RATIOS_LABEL": "Λόγοι Αερίων",
        "DGA_SECTION_GASES_STANDARD": "IEC 60599 / IEC 60567",
        "DGA_SECTION_RATIOS_STANDARD": "IEC 60599",
        "DGA_SECTION_PHYSCHEM_STANDARD": "IEC 60422",
        "DGA_ALL_PROBLEMATIC_BTN": "DGA εκτός ορίων (όλοι οι Υ/Σ)",
        "DGA_PROBLEMATIC_BTN_SHORT": "Εκτός ορίων (όλοι οι Υ/Σ)",
        "DGA_HISTORY_BTN_SHORT": "Ιστορικό",
        "DGA_LIMIT_GOOD": "ΚΑΛΟ",
        "DGA_LIMIT_TOLERABLE": "ΑΝΕΚΤΟ",
        "DGA_LIMIT_POOR": "ΠΤΩΧΟ",
        "DGA_LIMIT_LABEL": "όριο",
        "TRANSFORMER_LABEL": "Μετασχηματιστής:",
        "ELEMENT_NO_DATA_INFO": "Δεν υπάρχουν καταχωρημένα στοιχεία για αυτό το στοιχείο.",
        "DGA_TRANSFORMER_NO_MEASUREMENTS_INFO": "Δεν υπάρχουν καταχωρημένες μετρήσεις συντήρησης για αυτό το στοιχείο.\nΧρησιμοποιήστε τα κουμπιά DGA παρακάτω για καταχώρηση μετρήσεων διαλυμένων αερίων.",
        "MAINT_FOLDERS_CREATE_FAILED_FMT": "Αποτυχία δημιουργίας δομής φακέλων συντήρησης.\nΗ καταχώρηση ακυρώθηκε.\n\n{error}",
        "GATE_FOLDERS_SYNC_CREATE_FAILED_FMT": "Αποτυχία συγχρονισμού φακέλων πυλών.\nΗ καταχώρηση στοιχείου ακυρώθηκε.\n\n{error}",
        "GATE_FOLDERS_SYNC_EDIT_FAILED_FMT": "Αποτυχία συγχρονισμού φακέλων πυλών.\nΟι αλλαγές ακυρώθηκαν.\n\n{error}",
        "ONEDRIVE_FOLDER_CREATE_FAILED_FMT": "Αδυναμία δημιουργίας φακέλου: {path}\n{error}",
        "SUBSTATION_FOLDER_BASE_NOT_FOUND": "Δεν βρέθηκε υποσταθμός για δημιουργία δομής φακέλων.",
        "DGA_TEMPLATE_NOT_FOUND_FMT": "Δεν βρέθηκε το πρότυπο DGA: {path}",
        "STARTUP_ONEDRIVE_SUMMARY_FMT": "Έλεγχος δομής OneDrive στην εκκίνηση:\n- Υποσταθμοί που ελέγχθηκαν: {substations_total}\n- Δομές φακέλων που συγχρονίστηκαν: {substations_synced}\n- Αποτυχίες φακέλων: {substations_failed}\n\nΈλεγχος αναφορών συντηρήσεων:\n- Συνδυασμοί συντήρησης/στοιχείου που ελέγχθηκαν: {reports_total}\n- Νέες αναφορές που δημιουργήθηκαν: {reports_generated}\n- Αναφορές που ήδη υπήρχαν (παραλείφθηκαν): {reports_skipped}\n- Αποτυχίες αναφορών: {reports_failed}\n\nΈλεγχος επανασύνδεσης:\n- Σύνδεσμοι media που προστέθηκαν: {media_linked}\n- Σύνδεσμοι αναφορών που προστέθηκαν: {report_links_added}\n- Σύνδεσμοι αναφορών ήδη έγκυροι: {report_links_existing}\n- Αρχεία αναφορών που λείπουν ακόμη: {report_files_missing}",
        "STARTUP_PROGRESS_TITLE": "Αρχικοποίηση σε εξέλιξη",
        "STARTUP_INITIALIZING": "Αρχικοποίηση...",
        "STARTUP_SYNC_DATA_ONEDRIVE": "Συγχρονισμός δεδομένων με OneDrive...",
        "SYNC_PROGRESS_PREPARE": "Προετοιμασία συγχρονισμού...",
        "SYNC_PROGRESS_INBOX": "Επεξεργασία εισερχομένων αλλαγών...",
        "SYNC_PROGRESS_STRUCTURE": "Συγχρονισμός δομής φακέλων...",
        "SYNC_PROGRESS_REPORTS": "Αναγέννηση αναφορών συντήρησης...",
        "SYNC_PROGRESS_ASSETS": "Σύνδεση αρχείων και αναφορών...",
        "SYNC_PROGRESS_QUEUE": "Επεξεργασία ουράς εργασιών...",
        "SYNC_PROGRESS_FINALIZE": "Ολοκλήρωση συγχρονισμού...",
        "SYNC_PROGRESS_DONE": "Ο συγχρονισμός ολοκληρώθηκε.",
        "SYNC_MANUAL_FAILED_FMT": "Αποτυχία χειροκίνητου συγχρονισμού:\n{error}",
        "STARTUP_SYNC_PROMPT_TITLE": "Εντοπίστηκαν αλλαγές συγχρονισμού",
        "STARTUP_SYNC_PROMPT_MESSAGE": "Εντοπίστηκαν διαφορές στον κοινόχρηστο φάκελο από την τελευταία εκκίνηση.\nΘέλετε να εκτελεστεί συγχρονισμός τώρα;",
        "STARTUP_SYNC_DEFERRED_TOAST": "Ο συγχρονισμός εκκίνησης αναβλήθηκε. Μπορείτε να εκτελέσετε συγχρονισμό χειροκίνητα από το κουμπί Συγχρονισμός OneDrive.",
        "STARTUP_SYNC_DEFERRED_ACTION": "Συγχρονισμός OneDrive",
        "SETUP_WIZARD_INTRO": "Καλώς ήρθατε! Παρακαλώ ορίστε τις παρακάτω ρυθμίσεις για να ξεκινήσει η εφαρμογή.",
        "CONFIRM_DELETE_DGA_TITLE": "Επιβεβαίωση Διαγραφής",
        "CONFIRM_DELETE_DGA_MSG": "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτήν την αναφορά DGA;\n\nΗ διαγραφή είναι ΜΟΝΙΜΗ.",
        "MAINT_TYPE_DEFAULT": "Επαναληπτική συντήρηση",
        "MAINT_TYPE_LABEL": "Τύπος Συντήρησης:",
        "MAINT_USER_LABEL": "Χειριστής",
        "MANUFACTURER_HINT": "Κατασκευαστής",
        "MANUFACTURER_LABEL": "Κατασκευαστής",
        "MEASUREMENT_RESISTANCE_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ (Ohm)",
        "MISSING_SUBSTATIONS_WILL_CREATE": "Οι ακόλουθοι υποσταθμοί δεν υπάρχουν και θα δημιουργηθούν:",
        "MODELS_BUTTON": "Διαχείριση Τύπων Στοιχείων",
        "MODEL_ADDED": "Μοντέλο προστέθηκε!",
        "MODEL_CHECK_TITLE": "Έλεγχος Μοντέλου",
        "MODEL_DELETED": "Μοντέλο διαγράφηκε επιτυχώς!",
        "MODEL_HINT": "Μοντέλο",
        "MODEL_LABEL": "Μοντέλο",
        "MODEL_NAME_REQUIRED": "Το όνομα του μοντέλου είναι υποχρεωτικό!",
        "MODEL_NOT_FOUND": "Μοντέλο δεν βρέθηκε!",
        "MODEL_NOT_USED": "Το μοντέλο δεν χρησιμοποιείται από κανένα στοιχείο.",
        "MODEL_POWER_NUM": "Η ονομαστική ισχύς πρέπει να είναι αριθμός!",
        "MODEL_SELECT_PROMPT": "Επιλέξτε μοντέλο",
        "MODEL_SERVICE_CYCLE_NUM": "Ο κύκλος συντήρησης πρέπει να είναι αριθμός!",
        "MODEL_VERSION_HINT": "Έκδοση",
        "MODEL_VERSION_LABEL": "Έκδοση Μοντέλου",
        "MODE_LABEL_LOCAL": "Πηγή: Τοπική Βάση",
        "MONTHS": [
            "Ιανουάριος",
            "Φεβρουάριος",
            "Μάρτιος",
            "Απρίλιος",
            "Μάιος",
            "Ιούνιος",
            "Ιούλιος",
            "Αύγουστος",
            "Σεπτέμβριος",
            "Οκτώβριος",
            "Νοέμβριος",
            "Δεκέμβριος",
        ],
        "MONTH_LABEL": "Μήνας:",
        "NAME_LABEL": "Όνομα:",
        "NAME_REQUIRED": "Το όνομα είναι υποχρεωτικό",
        "NEW_MODELS_HEADER": "[b]Νέα Μοντέλα (θα προστεθούν):[/b]",
        "NEW_SUBSTATIONS_TITLE": "Νέοι Υποσταθμοί Εντοπίστηκαν",
        "NEXT": "Επόμενη",
        "NO_AVAILABLE_RESPONSIBLE": "Δεν υπάρχει διαθέσιμος υπεύθυνος συντήρησης με τα απαιτούμενα δικαιώματα. Προσθέστε ή ενημερώστε προσωπικό.",
        "NO_ELEMENTS": "Κανένα στοιχείο",
        "NO_ELEMENTS_FOR_ITEM": "Δεν υπάρχουν καταχωρημένα στοιχεία για αυτό το αντικείμενο.",
        "NO_ELEMENTS_IN_SUBSTATION": "Δεν υπάρχουν στοιχεία σε αυτόν τον υποσταθμό",
        "NO_ELEMENTS_PAREN": "(Κανένα στοιχείο)",
        "NO_INACTIVE_ELEMENTS": "Δεν υπάρχουν ανενεργά στοιχεία σε αυτόν τον υποσταθμό",
        "NO_INSPECTIONS": "Δεν υπάρχουν εγγραφές επιθεώρησης. Θέλετε να δημιουργήσετε μια;",
        "NO_LEAK_ENTRIES": "Δεν υπάρχουν καταχωρήσεις διαρροών για το έτος.",
        "NO_MAINTENANCES": "Δεν υπάρχουν αρχεία συντήρησης",
        "NO_MAINTENANCE_HISTORY": "Δεν υπάρχει ιστορικό συντηρήσεων για αυτό το στοιχείο",
        "NO_MAINT_FOR_SUBSTATION": 'No maintenance records for substation "{substation_name}".\nUse the button above to add one.',
        "NO_MODELS": "Κανένα μοντέλο",
        "NO_PEOPLE": "Δεν υπάρχουν καταχωρημένοι υπάλληλοι. Προσθέστε προσωπικό.",
        "NO_RECORD_ELEMENTS": "Δεν υπάρχουν στοιχεία για αυτήν τη συντήρηση.",
        "NO_SUBSTATIONS": "Δεν υπάρχουν υποσταθμοί!",
        "NO_USER_LOGGED_IN": "Δεν έχει συνδεθεί χρήστης",
        "OBSERVATIONS_HINT": "Παρατηρήσεις",
        "OPENPYXL_MISSING": "openpyxl δεν είναι εγκατεστημένο!",
        "OPENPYXL_MISSING_EXCEL_EXPORT": "Δεν βρέθηκε το πακέτο openpyxl. Εγκαταστήστε το για εξαγωγή Excel.",
        "OPEN_FILE_ERROR_PREFIX": "Αποτυχία ανοίγματος αρχείου:\n",
        "OPEN_FILE_ERROR_TITLE": "Σφάλμα",
        "OPEN_FILE_NOT_FOUND": "Το αρχείο δεν βρέθηκε!",
        "OPEN_FOLDER": "Άνοιγμα φακέλου",
        "OPEN_LOCAL_DB_TITLE": "Άνοιγμα Τοπικής Βάσης",
        "OPERATING_STATUS": ["Ενεργή", "Ανενεργή"],
        "OPERATING_STATUS_LABEL": "Λειτ. Κατάσταση",
        "ORG_SHORT": "ΔΕΕΔ",
        "OVERALL_COMMENTS_HINT": "Γενικά σχόλια για την συντήρηση...",
        "OVERALL_COMMENTS_LABEL": "Γενικά Σχόλια Συντήρησης:",
        "ONEDRIVE_MEDIA_LABEL": "Σύνδεσμος Φάκελου Εικόνων/Video (OneDrive):",
        "OPEN_ONEDRIVE_FOLDER": "Φάκελος OneDrive",
        "PAGE_LABEL_TEMPLATE": "Σελίδα {page}",
        "PAGE_SIZE_LABEL": "Αντικείμενα/σελίδα",
        "PAGE_SIZE_OPTIONS": [
            "10",
            "20",
            "30",
            "50",
        ],
        "PDF_BUTTON": "PDF",
        "PDF_CREATED": "Το PDF δημιουργήθηκε:\n{path}",
        "PDF_CREATED_TITLE": "PDF Δημιουργήθηκε",
        "PDF_CREATE_FAILED": "Αποτυχία δημιουργίας PDF:\n{err}",
        "PDF_ELEMENT_CREATED_FMT": 'Το αρχείο PDF για το στοιχείο "{element_name}"\nδημιουργήθηκε επιτυχώς!\n\nΑποθηκεύτηκε στο:\n{pdf_path}',
        "PEOPLE_BUTTON": "Διαχείριση Προσωπικού",
        "PEOPLE_SUMMARY": "Υπεύθυνος: {resp} | Ομάδα: {crew}",
        "PERSON_IN_USE": "Αυτό το άτομο έχει χρησιμοποιηθεί στη συντήρηση. Διαγράψτε μόνο αφού αφαιρεθεί από το ιστορικό ή απενεργοποιήστε το.",
        "PERSON_NOT_FOUND": "Το άτομο δεν βρέθηκε!",
        "PHASE_TO_PHASE_LABEL": "FA-FA",
        "PHASE_TO_PHASE_LABEL_COLON": "FA-FA:",
        "PICKER_EMPTY_SELECTION": "Ο επιλογέας επέστρεψε κενή επιλογή (None).",
        "PLEASE_SELECT_BREAKER_CATEGORY": "Παρακαλώ επιλέξτε κατηγορία διακόπτη!",
        "PLEASE_SELECT_EML": "Please select a .eml file!",
        "PLEASE_SELECT_OR_ADD_SUBSTATION": "Παρακαλώ επιλέξτε έναν υποσταθμό ή προσθέστε έναν νέο.",
        "PLEASE_SELECT_PDF": "Please select a PDF file!",
        "PREVIOUS": "Προηγούμενη",
        "PRINT": "Εκτύπωση",
        "PROMPT_SUBSTATION_NOT_FOUND_TITLE": "Ο υποσταθμός δε βρέθηκε",
        "PROMPT_SUBSTATION_SELECT": "Επιλέξτε υποσταθμό για εισαγωγή:",
        "RATED_POWER_HINT": "π.χ. 50",
        "RECORD_NOT_FOUND": "Η εγγραφή δεν βρέθηκε.",
        "REGION_HINT": "Περιοχή",
        "REGION_LABEL": "Περιοχή:",
        "RESPONSIBLE_LABEL": "Υπεύθυνος:",
        "RESPONSIBLE_NOT_FOUND_TITLE": "Ο υπεύθυνος δε βρέθηκε",
        "RESPONSIBLE_REQUIRED": "Απαιτείται υπεύθυνος συντήρησης!",
        "RETRY": "Ξαναδοκίμασε",
        "RETRY_LOAD": "Επανάληψη φόρτωσης",
        "ROLE_LABEL": "Ρόλος:",
        "SEARCH_HINT": "Αναζήτηση (όνομα/ημερομηνία)",
        "SELECT_ALL_BTN": "Επιλογή Όλων",
        "SELECT_AT_LEAST_ONE_ELEMENT": "Πρέπει να επιλέξετε τουλάχιστον ένα στοιχείο!",
        "SELECT_MONOGRAM_PDF_TITLE": "Επιλέξτε μονογραμμικό PDF",
        "SELECT_PROMPT": "Επιλογή",
        "SELECT_SUBSTATION": "Επιλογή Υποσταθμού:",
        "SELECT_SUBSTATION_BTN": "Επιλογή Υποσταθμού",
        "SERIAL_NUMBER_HINT": "Σειριακός Αριθμός",
        "SERIAL_NUMBER_LABEL": "Σειριακός Αριθμός",
        "SETTINGS_TOOLTIP": "Ρυθμίσεις",
        "SF6_BUTTON": "SF6",
        "SF6_LEAK_METHODOLOGY_REQUIRED": "Η διαρροή SF6 απαιτεί μεθοδολογία (Πλήρωση/Αντικατάσταση).",
        "SF6_MANAGEMENT_TITLE": "Διαχείριση SF6",
        "SF6_SUBSTATION_HEADER": "Υποσταθμός",
        "SF6_SUMMARY_FMT": "Εγκατεστημένο SF6 (ενεργά): {installed_sf6:.2f} kg | Ενεργά στοιχεία SF6: {active_elements} | Υποσταθμοί με SF6: {active_substations}\nΈτος: {year_value} | Διαρροές: {total_leakage:.2f} kg | Ποσοστό: {percentage:.2f}%",
        "SF6_SUMMARY_LEAKS_YEAR_FMT": "ΔΙΑΡΡΟΕΣ {year} (kg)",
        "SF6_SUMMARY_PERCENT_YEAR_FMT": "ΠΟΣΟΣΤΟ ΔΙΑΡΡΟΩΝ {year}",
        "SF6_SUMMARY_SHEET_TITLE": "Σύνοψη",
        "SF6_SUMMARY_TOTAL_INSTALLED": "ΣΥΝΟΛΙΚΗ ΕΓΚΑΤΕΣΤΗΜΕΝΗ ΠΟΣΟΤΗΤΑ (kg)",
        "SF6_TABLE_HEADERS": [
            "Α/Α",
            "ΒΟΚ ή ΠΕΡΙΟΧΗ",
            "ΕΓΚΑΤΑΣΤΑΣΗ (Πχ. Όνομα Υ/Σ)",
            "ΜΟΝΑΔΑ ΜΕΤΡΗΣΗΣ",
            "ΠΛΗΡΩΣΗ Ή ΑΝΤΙΚΑΤΑΣΤΑΣΗ (ΜΕΘΟΔΟΛΟΓΙΑ)",
            "ΣΥΝΟΛΙΚΗ ΕΓΚΑΤΕΣΤΗΜΕΝΗ ΠΟΣΟΤΗΤΑ (kg)",
            "ΠΟΣΟΤΗΤΑ ΔΙΑΡΡΟΩΝ (kg)",
            "ΗΜ/ΝΙΑ",
            "ΥΠΕΥΘΥΝΟΣ ΣΥΝΕΡΓΕΙΟΥ",
            "ΥΠΟΓΡΑΦΗ",
        ],
        "SF6_TABLE_TITLE": "ΠΙΝΑΚΑΣ 4: ΠΗΓΗ ΕΚΠΟΜΠΩΝ ΑΠΟ ΕΞΟΠΛΙΣΜΟ ΧΡΗΣΗΣ SF6",
        "SF6_TOTAL_LEAKAGE_HEADER": "Σύνολο Διαρροών (kg)",
        "SHARE_BUTTON": "Κοινοποίηση",
        "SUMMARY_BUTTON": "Σύνοψη",
        "LATER_BUTTON": "Αργότερα",
        "CHANGE_LOG_SUMMARY_TITLE": "Σύνοψη αλλαγών",
        "CHANGE_LOG_EMPTY": "Το change log είναι κενό.",
        "CHANGE_LOG_NO_MAJOR_ISSUES": "χωρίς σημαντικές παρατηρήσεις",
        "CHANGE_LOG_PENDING_REVIEW_TITLE": "Εκκρεμείς αλλαγές",
        "CHANGE_LOG_PENDING_REVIEW": "Το change log περιέχει εκκρεμείς αλλαγές.",
        "CHANGE_LOG_PENDING_REVIEW_STARTUP": "Το change log περιέχει εκκρεμείς αλλαγές από προηγούμενη χρήση.",
        "CHANGE_LOG_PENDING_REVIEW_AFTER_SHARE": "Η κοινοποίηση ξεκίνησε. Θέλετε να καθαρίσετε τώρα το change log;",
        "SHOW_ALL_SUBSTATIONS": "Προβολή Όλων των Υποσταθμών",
        "SHOW_DB_BUTTON": "Προβολή βάσης υποσταθμών",
        "SINGLE_LINE": "Μονογραμμικό",
        "SORT_OPTIONS": [
            "Ημερομηνία (φθίνουσα)",
            "Ημερομηνία (αύξουσα)",
            "Υποσταθμός A-Ω",
        ],
        "STAFF_LOAD_FAILED": "Αποτυχία φόρτωσης διαχείρισης προσωπικού.",
        "SUBSTATION_ADDED": "Ο υποσταθμός {substation_name} προστέθηκε!",
        "SUBSTATION_EXISTS": "Ο υποσταθμός υπάρχει ήδη.",
        "SUBSTATION_INSPECTION_COUNT_FMT": "{count} εγγραφές επιθεώρησης για υποσταθμό {substation_name}",
        "SUBSTATION_INSPECTION_HISTORY_TITLE_FMT": "Ιστορικό Επιθεωρήσεων - {substation_name}",
        "SUBSTATION_IS_THESSALONIKI": "ΥΣ Θεσσαλονίκης",
        "SUBSTATION_LABEL": "Υποσταθμός:",
        "SUBSTATION_LABEL_PLAIN": "Υποσταθμός",
        "SUBSTATION_NAME_HINT": "Όνομα Υποσταθμού",
        "SUBSTATION_NAME_LABEL": "Όνομα Υποσταθμού:",
        "SUBSTATION_NEW_HINT": "Νέο όνομα υποσταθμού",
        "SUBSTATION_NOT_FOUND": "Ο υποσταθμός δεν βρέθηκε.",
        "SURNAME_LABEL": "Επώνυμο:",
        "SURNAME_ROLE_REQUIRED": "Το επώνυμο και ο ρόλος είναι υποχρεωτικά!",
        "TEMPLATE_ELEMENTS_EXAMPLES": [
            (
                "Υποσταθμός Α",
                "Διακόπτης ΜΤ",
                "Main Breaker",
                "SN-001",
                "2025-01-20",
                "SF6",
                "Κεντρικός",
                "Ενεργή",
                "ΠΥΛΗ 1",
                "SF6-400",
                "ABB",
                "Εσωτερικού",
            ),
            (
                "Υποσταθμός Α",
                "Μετασχηματιστής 150/20KV",
                "Transformer 1",
                "SN-002",
                "2025-01-18",
                "",
                "",
                "Ενεργή",
                "ΠΥΛΗ 1",
                "GEAFOL",
                "Siemens",
                "Εξωτερικού",
            ),
        ],
        "TEMPLATE_ELEMENTS_HEADERS": [
            "Substation Name",
            "Element Type",
            "Name",
            "Serial Number",
            "Maintenance Date",
            "Τύπος Διακόπτη",
            "Breaker Role",
            "Operating Status",
            "Gate",
            "Model Name",
            "Model Manufacturer",
            "Model Installation Space",
        ],
        "TEMPLATE_ELEMENTS_TITLE": "Template Στοιχείων",
        "TEMPLATE_SUBSTATIONS_EXAMPLES": [
            ("Υποσταθμός Α", "https://maps.google.com/?q=example1", "2025-01-15"),
            ("Υποσταθμός Β", "https://maps.google.com/?q=example2", "2025-01-20"),
        ],
        "TEMPLATE_SUBSTATIONS_HEADERS": ["Name", "Location", "Adoption Date"],
        "TEMPLATE_SUBSTATIONS_TITLE": "Template Υποσταθμών",
        "TOOLTIP_DELETE": "Διαγραφή",
        "TOOLTIP_EDIT": "Επεξεργασία",
        "TOOLTIP_INSPECTION": "Επιθεώρηση",
        "TOOLTIP_MAINTENANCE": "Συντήρηση",
        "TOOLTIP_MANUAL": "Manual",
        "TOOLTIP_VIEW": "Προβολή",
        "UNREGISTERED_PLACEHOLDER": "(Μη καταχωρημένο)",
        "UNSUPPORTED_FILE_FORMAT": "Μη υποστηριζόμενη μορφή αρχείου",
        "USER_LABEL": "Χρήστης:",
        "VIDAR_HINT": "0.0",
        "VIDAR_LABEL_FB": "FB-FB:",
        "VIDAR_LABEL_FC": "FC-FC:",
        "VIDAR_SECTION_TITLE": "Έλεγχος Κενού VIDAR",
        "VIDAR_VACUUM_CHECK_LABEL": "ΈΛΕΓΧΟΣ ΚΕΝΟΥ (VIDAR):",
        "VIEW_ACTIVE_ELEMENTS": "Προβολή ενεργών στοιχείων ({count})",
        "VIEW_ELEMENT_TITLE": "Προβολή Στοιχείου",
        "VIEW_FULL_MAINTENANCE": "Πλήρης αναφορά",
        "VIEW_PROMPT": "Επιλέξτε τι θέλετε να δείτε:",
        "VIEW_SELECTION_TITLE": "Επιλογή Προβολής",
        "VIEW_SHORT": "Προβ.",
        "VOLTAGE_LEVELS": [
            "(Κενό)",
            "150/20KV",
            "20KV",
            "150KV",
            "20KV/400V",
        ],
        "YEAR_LABEL": "Έτος:",
    },
    "TITLES": {
        "ERROR": "Σφάλμα",
        "IMPORT_ANDROID": "Εισαγωγή αλλαγών από Android",
        "IMPORT_ELEMENTS": "Εισαγωγή Στοιχείων",
        "IMPORT_MENU": "Εισαγωγή/Εξαγωγή δεδομένων",
        "IMPORT_SUBSTATIONS_TITLE": "Εισαγωγή Υποσταθμών",
        "INFO": "Πληροφορίες",
        "INSPECTION_DETAILS": "Λεπτομέρειες Επιθεώρησης",
        "INSPECTION_ENTRY": "Καταχώρηση Επιθεώρησης",
        "INSPECTION_HISTORY": "Ιστορικό Επιθεωρήσεων",
        "LOGIN": "Σύνδεση",
        "PREVIEW_CHANGELOG": "Προεπισκόπηση αρχείου αλλαγών",
        "SETTINGS": "Ρυθμίσεις",
        "SETUP_WIZARD": "Αρχική Ρύθμιση Εφαρμογής",
        "SYNC_NOTIFICATION": "Συγχρονισμός",
        "SYNC_SETTINGS": "Ρυθμίσεις Sync",
        "SUCCESS": "Επιτυχία",
        "WARNING": "Προειδοποίηση",
    },
}

STRINGS_EN = {
    "BUTTONS": {
        "IMPORT": "Import",
        "ADD": "Add",
        "VIEW": "View",
        "REFRESH": "Refresh",
        "OPEN": "Open",
        "REPLACE": "Replace",
        "SKIP": "Skip",
        "REPLACE_ALL": "Replace All",
        "SKIP_ALL": "Skip All",
        "CONFIRM": "Confirm",
        "EDIT": "Edit",
        "LIST": "List",
        "CANCEL": "Cancel",
        "EMAIL": "Email",
        "APPLY": "Apply",
        "BACKUP_APPLY": "Backup & Apply",
        "CLOSE": "Close",
        "CONTINUE": "Continue",
        "INSPECTIONS": "Inspections",
        "SAVE": "Save",
        "SETTINGS": "Settings",
        "BACK": "Back",
        "MAINTENANCE": "Maintenance",
        "INSPECT": "Inspect",
        "DELETE": "Delete",
        "UPDATE": "Update",
        "YES": "Yes",
        "NO": "No",
        "OK": "OK",
        "COPY": "Copy",
        "BROWSE_FILE": "Browse file",
        "ADD_MAINTENANCE": "+ Add New Maintenance",
        "ADD_MODEL": "+ Add New Model",
        "LOGIN": "Login",
        "LOGOUT": "Logout",
        "RESET": "Reset",
        "SYNC_NOW": "Sync now",
        "SKIP_FOR_NOW": "Skip for now",
    },
    "TITLES": {
        "ERROR": "Error",
        "SUCCESS": "Success",
        "INFO": "Info",
        "IMPORT_MENU": "Import from file",
        "IMPORT_ANDROID": "Import changes from Android",
        "IMPORT_ELEMENTS": "Import Elements",
        "PREVIEW_CHANGELOG": "Change log preview",
        "INSPECTION_ENTRY": "Inspection Entry",
        "INSPECTION_HISTORY": "Inspection History",
        "INSPECTION_DETAILS": "Inspection Details",
        "IMPORT_SUBSTATIONS_TITLE": "Import Substations",
        "SETTINGS": "Settings",
        "SETUP_WIZARD": "Initial App Setup",
        "SYNC_NOTIFICATION": "Sync",
        "SYNC_SETTINGS": "Sync Settings",
        "WARNING": "Warning",
        "LOGIN": "Login",
    },
    "MESSAGES": {
        "APP_TITLE": "HEDNO Substations DEDD/KSMTH/TEI",
        "APP_INFO_SHORT": "App Info",
        "APP_INFO_TITLE": "Application Information",
        "APP_INFO_BODY": (
            "HEDNO Substations DEDD/KSMTH/TEI\n"
            "Version: {version}\n"
            "DB Version: {db_version}\n"
            "Compatibility: {compat_status}\n\n"
            "Application features:\n"
            "• View and manage substation database\n"
            "• Add/edit/delete substations and elements\n"
            "• Circuit breaker categories (SF6/Oil/Low Oil)\n"
            "• Manage element types (models/manufacturers/cycles)\n"
            "• Maintenance records\n"
            "• Import maintenance from e-mail (.eml)\n"
            "• Maintenance history (all/by substation)\n"
            "• Breaker measurements (insulation/passage/operations)\n"
            "• SF6 gas quality & leaks (kg)\n"
            "• SF6 management (leakage report by year)\n"
            "• Export SF6 Excel reports (summary & per substation)\n"
            "• Print maintenance PDF reports\n"
            "• Inspections (entry/view/history)\n"
            "• Isolation requests\n"
            "• Import substations/elements from CSV/Excel\n"
            "• PDF & Excel reports\n\n"
            "App folder: {app_dir}"
        ),
        "LOADING": "Loading...",
        "COPY": "Copy",
        "DASH": "-",
        "ENTER_PATH": "Please enter a path or select a file!",
        "IMPORT_MENU_PROMPT": "Select what you want to import/export:",
        "IMPORT_ELEMENTS_BUTTON": "Import Elements from File",
        "IMPORT_EXPORT_DB_BUTTON": "Export Full Database (Excel)",
        "IMPORT_TEMPLATE_PROMPT": "Or create an import template:",
        "IMPORT_TEMPLATE_ELEMENTS_BUTTON": "Create Import Template",
        "IMPORT_OR_SELECT_FROM_LIST": "Or select from the list:",
        "FILE_PATH_LABEL": "File path:",
        "FILE_PATH_HINT": "File path",
        "FILE_NOT_FOUND": "File not found!",
        "PLEASE_SELECT_PDF": "Please select a PDF file!",
        "UNSUPPORTED_FILE_FORMAT": "Unsupported file format",
        "FILE_HAS_NO_DATA": "The file contains no data.",
        "IMPORT_FAILED": "Import failed:",
        "IMPORT_SUCCESS": "Import successful.",
        "SELECT_MONOGRAM_PDF_TITLE": "Select single-line PDF",
        "CHANGELOG_FILE_LABEL": "Change log file path (.jsonl/.txt):",
        "NO_SUBSTATIONS": "No substations!",
        "EMPTY_DB": "Empty database",
        "ADD_NEW_SUBSTATION_PROMPT": "Or add a new substation:",
        "PLEASE_SELECT_OR_ADD_SUBSTATION": "Please select a substation or add a new one.",
        "ENTER_SUBSTATION_NAME": "Please enter substation name!",
        "SUBSTATION_LABEL": "Substation:",
        "SUBSTATION_NAME_LABEL": "Substation Name:",
        "SUBSTATION_NAME_HINT": "Substation Name",
        "SUBSTATION_NEW_HINT": "New substation name",
        "SUBSTATION_IS_THESSALONIKI": "Thessaloniki Substation",
        "SUBSTATION_ADDED": "Substation added!",
        "SUBSTATION_EXISTS": "Substation already exists.",
        "SELECT_SUBSTATION": "Select Substation:",
        "SELECT_SUBSTATION_BTN": "Select Substation",
        "PROMPT_SUBSTATION_NOT_FOUND_TITLE": "Substation not found",
        "PROMPT_SUBSTATION_SELECT": "Select substation for import:",
        "SUBSTATION_NOT_FOUND": "Substation not found.",
        "MISSING_SUBSTATIONS_WILL_CREATE": "The following substations do not exist and will be created:",
        "NEW_SUBSTATIONS_TITLE": "New Substations Detected",
        "MAINTENANCE_SAVED_CHANGELOG": "Maintenance was recorded in the change log.",
        "UNDONE_MAINTENANCES_LABEL": "Undone Maintenances",
        "TASKS_LEFT_LABEL": "Tasks left",
        "MARK_COMPLETE_LABEL": "Mark complete",
        "MEASUREMENTS_HISTORY_LABEL": "Measurements History",
        "MEASUREMENTS_HISTORY_BUTTON": "Measurements History",
        "ONLY_FAILED_LABEL": "Only failed",
        "MAINTENANCE_DELETED": "Maintenance deleted!",
        "MAINTENANCE_NOT_FOUND": "Maintenance not found.",
        "NO_MAINTENANCES": "No maintenance records",
        "NO_MAINT_FOR_SUBSTATION": (
            'No maintenance records for substation "{substation_name}".\n'
            "Use the button above to add one."
        ),
        "MAINT_HISTORY_LABEL": "Maintenance History",
        "DGA_LABEL": "Physicochemical/Gas Chromatography",
        "DGA_NEW_MEASUREMENT_LABEL": "New DGA Measurement",
        "DGA_ADD_MEASUREMENT_SHORT": "New Measurement",
        "DGA_MAINT_FORM_TITLE": "Record DGA Measurement",
        "DGA_START_BUTTON": "Start DGA",
        "DGA_SELECT_TRANSFORMER_REQUIRED": "Please select a transformer",
        "DGA_MAINT_NAME_FMT": "DGA - {element_name} ({date})",
        "DGA_SUBSTATION_TITLE_FMT": "{dga_label} - {substation_name}",
        "DGA_NO_MEASUREMENTS_FOR_SUBSTATION": "No DGA measurements for this substation",
        "DGA_MEASUREMENTS_COUNT_FMT": "{element_name} (S/N: {serial_number}) - {count} measurements",
        "DGA_MEASUREMENTS_FOR_FMT": "DGA measurements for: {element_name}",
        "DGA_VIEW_HISTORY_BUTTON": "View Measurement History",
        "DGA_ELEMENT_NOT_FOUND": "Element not found.",
        "DGA_SUBSTATION_NOT_FOUND": "Substation not found for DGA entry.",
        "DGA_RECORD_NOT_FOUND": "DGA record not found.",
        "DGA_POPUP_TITLE_FMT": "DGA - {element_name}",
        "DGA_POPUP_EDIT_TITLE_FMT": "Edit DGA - {element_name}",
        "DGA_SAVE_SUCCESS_FMT": "DGA report saved:\n{path}",
        "DGA_SAVE_FAILED_FMT": "Failed to save DGA:\n{error}",
        "DGA_HISTORY_TITLE_FMT": "DGA History - {element_name}",
        "DGA_HISTORY_ROW_FMT": "Measurement: {measurement_date} | Sampling: {sampling_date} | Created: {created_at}",
        "DGA_OPEN_REPORT_BUTTON": "Open Report",
        "DGA_NO_MEASUREMENTS_FOR_ELEMENT": "No DGA measurements found for this element.",
        "DGA_SAMPLING_DATE_LABEL": "Sampling Date",
        "DGA_MEASUREMENT_DATE_LABEL": "Measurement Date",
        "DGA_SAMPLE_POINT_LABEL": "Sample Point",
        "DGA_METHOD_LABEL": "Method",
        "DGA_SAMPLING_RESPONSIBLE_LABEL": "Sampling Responsible",
        "DGA_MEASUREMENT_RESPONSIBLE_LABEL": "Measurement Responsible",
        "DGA_SAMPLE_TEMPERATURE_LABEL": "Sample Temperature",
        "DGA_DENSITY_LABEL": "Density",
        "DGA_HUMIDITY_LABEL": "Humidity",
        "DGA_DIELECTRIC_STRENGTH_LABEL": "Dielectric Strength",
        "DGA_LOSS_FACTOR_LABEL": "Loss Factor",
        "DGA_SURFACE_TENSION_LABEL": "Surface Tension",
        "DGA_NOTES_LABEL": "Notes",
        "DGA_BADGE_BAD": "OUT OF LIMITS",
        "DGA_BADGE_WARN": "TOLERABLE / WARNING",
        "DGA_BADGE_OK": "OK",
        "DGA_LEGEND_TITLE": "Legend",
        "DGA_LEGEND_OK_COLOR": "Green=OK",
        "DGA_LEGEND_WARN_COLOR": "Yellow=TOLERABLE/Warning",
        "DGA_LEGEND_BAD_COLOR": "Red=OUT OF LIMITS",
        "DGA_LIMIT_FMT": "limit: {limit}",
        "DGA_GOOD_TOLERABLE_FMT": "good: {good} | tolerable: {tolerable}",
        "DGA_MORE_FMT": "+{remaining} more",
        "DGA_PROBLEMATIC_TITLE": "DGA Warnings / Out of Limits",
        "DGA_NO_PROBLEMATIC": "No DGA measurements with warnings or out of limits found.",
        "DGA_PROBLEMATIC_COUNT_FMT": "Found {count} measurements with warnings/out of limits.",
        "DGA_MEAS_DATE_LABEL": "Meas. date",
        "DGA_STATUS_BAD_MSG": "Limit status: OUT OF LIMITS (RED)",
        "DGA_STATUS_WARN_MSG": "Limit status: TOLERABLE / WARNING (YELLOW)",
        "DGA_STATUS_OK_MSG": "Limit status: OK (GREEN)",
        "DGA_SECTION_META_LABEL": "Sampling / Measurement Details",
        "DGA_SECTION_GASES_LABEL": "Gases",
        "DGA_SECTION_PHYSCHEM_LABEL": "Physicochemical Measurements",
        "DGA_SECTION_RATIOS_LABEL": "Gas Ratios",
        "DGA_SECTION_GASES_STANDARD": "IEC 60599 / IEC 60567",
        "DGA_SECTION_RATIOS_STANDARD": "IEC 60599",
        "DGA_SECTION_PHYSCHEM_STANDARD": "IEC 60422",
        "DGA_ALL_PROBLEMATIC_BTN": "DGA out of limits (all substations)",
        "DGA_PROBLEMATIC_BTN_SHORT": "Out of limits (all substations)",
        "DGA_HISTORY_BTN_SHORT": "History",
        "DGA_LIMIT_GOOD": "GOOD",
        "DGA_LIMIT_TOLERABLE": "TOLERABLE",
        "DGA_LIMIT_POOR": "POOR",
        "DGA_LIMIT_LABEL": "limit",
        "TRANSFORMER_LABEL": "Transformer:",
        "ELEMENT_NO_DATA_INFO": "No registered data for this element.",
        "DGA_TRANSFORMER_NO_MEASUREMENTS_INFO": "There are no recorded maintenance measurements for this element.\nUse the DGA buttons below to record dissolved gas measurements.",
        "MAINT_FOLDERS_CREATE_FAILED_FMT": "Failed to create maintenance folder structure.\nThe entry was cancelled.\n\n{error}",
        "GATE_FOLDERS_SYNC_CREATE_FAILED_FMT": "Failed to sync gate folders.\nElement creation was cancelled.\n\n{error}",
        "GATE_FOLDERS_SYNC_EDIT_FAILED_FMT": "Failed to sync gate folders.\nChanges were cancelled.\n\n{error}",
        "ONEDRIVE_FOLDER_CREATE_FAILED_FMT": "Failed to create folder: {path}\n{error}",
        "SUBSTATION_FOLDER_BASE_NOT_FOUND": "Substation not found for folder structure creation.",
        "DGA_TEMPLATE_NOT_FOUND_FMT": "DGA template not found: {path}",
        "STARTUP_ONEDRIVE_SUMMARY_FMT": "OneDrive startup structure check:\n- Substations checked: {substations_total}\n- Folder structures synced: {substations_synced}\n- Folder failures: {substations_failed}\n\nMaintenance report check:\n- Maintenance/element pairs checked: {reports_total}\n- New reports generated: {reports_generated}\n- Reports already present (skipped): {reports_skipped}\n- Report failures: {reports_failed}\n\nRelink check:\n- Media links added: {media_linked}\n- Report links added: {report_links_added}\n- Report links already valid: {report_links_existing}\n- Report files still missing: {report_files_missing}",
        "STARTUP_PROGRESS_TITLE": "Initialization in Progress",
        "STARTUP_INITIALIZING": "Initializing...",
        "STARTUP_SYNC_DATA_ONEDRIVE": "Synchronizing data with OneDrive...",
        "SYNC_PROGRESS_PREPARE": "Preparing synchronization...",
        "SYNC_PROGRESS_INBOX": "Processing incoming changes...",
        "SYNC_PROGRESS_STRUCTURE": "Synchronizing folder structure...",
        "SYNC_PROGRESS_REPORTS": "Regenerating maintenance reports...",
        "SYNC_PROGRESS_ASSETS": "Relinking files and reports...",
        "SYNC_PROGRESS_QUEUE": "Processing queued jobs...",
        "SYNC_PROGRESS_FINALIZE": "Finalizing synchronization...",
        "SYNC_PROGRESS_DONE": "Synchronization completed.",
        "SYNC_MANUAL_FAILED_FMT": "Manual synchronization failed:\n{error}",
        "STARTUP_SYNC_PROMPT_TITLE": "Sync Changes Detected",
        "STARTUP_SYNC_PROMPT_MESSAGE": "Detected differences in the shared sync folder since your last startup.\nDo you want to run synchronization now?",
        "STARTUP_SYNC_DEFERRED_TOAST": "Startup sync was deferred. You can run sync manually from the OneDrive Sync button.",
        "STARTUP_SYNC_DEFERRED_ACTION": "OneDrive Sync",
        "SETUP_WIZARD_INTRO": "Welcome! Please configure the settings below to get started.",
        "CONFIRM_DELETE_DGA_TITLE": "Delete Confirmation",
        "CONFIRM_DELETE_DGA_MSG": "Are you sure you want to delete this DGA report?\n\nDeletion is PERMANENT.",
        "MAINTENANCE_NAME_FMT": "Subst. {substation_name} - {date}",
        "NO_RECORD_ELEMENTS": "No elements for this maintenance.",
        "DATE_TIME_LABEL": "Date & Time:",
        "DATE_REQUIRED": "Date is required!",
        "DATE_PREFIX": "Date:",
        "MAINT_TYPE_LABEL": "Maintenance Type:",
        "MAINTENANCE_TYPES": [
            "Recurring maintenance",
            "Fault",
            "Physicochemical/Gas Chromatography",
        ],
        "MAINT_TYPE_DEFAULT": "Recurring maintenance",
        "RESPONSIBLE_LABEL": "Maintenance Responsible (required):",
        "RESPONSIBLE_REQUIRED": "Maintenance responsible is required!",
        "CREW_LABEL": "Maintenance Crew (optional):",
        "OVERALL_COMMENTS_LABEL": "General Maintenance Comments:",
        "ONEDRIVE_MEDIA_LABEL": "Photos/Videos Folder Link (OneDrive):",
        "OPEN_ONEDRIVE_FOLDER": "OneDrive Folder",
        "ELEMENTS_SECTION_LABEL": "Elements maintained (at least 1):",
        "NO_ELEMENTS_IN_SUBSTATION": "There are no elements in this substation",
        "SELECT_AT_LEAST_ONE_ELEMENT": "You must select at least one element!",
        "ADD_ELEMENT_BEFORE_CONTINUE": "Add at least one element before continuing.",
        "INSPECTION_SAVED": "Inspection saved!",
        "INSPECTION_ROWS": [
            "Check external & internal doors of the substation",
            "Check interior of the building (lighting, air conditioning, etc)",
            "Check surrounding area (vegetation, trees, lighting, etc)",
            "General inspection of fire protection equipment",
            "Visual check for oil leakage/level/temperature, silica gel on the transformer",
            "Visual check for oil leakage or SF6 pressure or air pressure on 150kV & 20kV circuit breakers",
            "Check transformer fan operation",
            "Visual check of injection transformer, CTs, VTs, service transformer, neutral resistor (temperature)",
            "Visual check of insulators (pollution, scratches, etc)",
            "Visual check of fuses and capacitors",
            "Check markings on transformer panels, 150kV & 20kV switchgear",
            "Take photo when required",
            "Visual check of gates, A/Z and general structures for nests, breaks, insulators, branches, wires, etc",
            "Visual check on 20kV switchgear panels (alarms, indications, doors) and check for noise/ionization",
            "Check for humidity (basement, cable channels), dehumidifiers, heaters, portable fire extinguishers",
            "Check 110V charger visually with voltage/current measurement and recording",
            "Check for DC loss alarm on main DC panel",
            "Visual check for leaks in battery elements",
            "Visual check of generators and their bridges on the 1st pole of each line (broken, insulators, etc)",
            "Check operation of digital system (operations, indications, markings)",
            "PC power supply",
            "Views and suggestions for better operation of equipment and building in general",
        ],
        "INSPECTION_SECTION_2": "[b]Substation Areas Check[/b]",
        "INSPECTION_SECTION_3": "[b]150/20kV Transformer & 150kV/20kV Breakers[/b]",
        "INSPECTION_SECTION_3A": "[b]Outdoor 20 kV gates[/b]",
        "INSPECTION_SECTION_3B": "[b]Outdoor 20 kV gates[/b]",
        "INSPECTION_SECTION_4": "[b]Control building & Aux. Services[/b]",
        "INSPECTION_SECTION_5": "[b]Line Disconnectors[/b]",
        "INSPECTION_SECTION_6": "[b]Control PC[/b]",
        "INSPECTION_SECTION_7": "[b]Views[/b]",
        "INSPECTION_BASE_FIELDS": [
            "Substation",
            "Form No.",
            "Month",
            "Inspector Name",
            "Region",
            "Day",
            "Year",
            "Date",
        ],
        "IMPORT_INSPECTIONS_TITLE": "Import Inspections",
        "IMPORT_INSPECTIONS_DONE": "Import completed ({inserted} records).",
        "IMPORT_INSPECTIONS_DIALOG": "Import inspections from file",
        "NO_INSPECTIONS": "There are no inspection records. Do you want to create one?",
        "INSPECTION_COUNT_FMT": "{count} inspection records",
        "SUBSTATION_INSPECTION_HISTORY_TITLE_FMT": "Inspection History - {substation_name}",
        "SUBSTATION_INSPECTION_COUNT_FMT": "{count} inspection records for substation {substation_name}",
        "SUBSTATION_LABEL_PLAIN": "Substation",
        "DATE_PLAIN": "Date",
        "MEASUREMENT_RESISTANCE_HEADER": "RESISTANCE MEASUREMENT (Ohm)",
        "NO_PEOPLE": "No people recorded. Please add staff.",
        "SURNAME_LABEL": "Surname:",
        "NAME_LABEL": "Name:",
        "ROLE_LABEL": "Role:",
        "EMAIL_LABEL": "Email:",
        "EMAIL_RECIPIENT_LABEL": "Email report recipients",
        "ACTIVE_LABEL": "Active",
        "STAFF_LOAD_FAILED": "Failed to load staff management.",
        "PERSON_NOT_FOUND": "Person not found!",
        "EDIT_PERSON_TITLE": "Edit Person",
        "SURNAME_ROLE_REQUIRED": "Surname and role are required!",
        "PERSON_IN_USE": "This person has been used in maintenance. Delete only after removing from history or deactivate.",
        "CONFIRM_DELETE_PERSON_FMT": 'Are you sure you want to delete\nperson "{person_name}"?',
        "NO_AVAILABLE_RESPONSIBLE": "No available maintenance responsible with required permissions. Add or update staff.",
        "SF6_LEAK_METHODOLOGY_REQUIRED": "SF6 leakage requires a methodology (Filling/Replacement).",
        "GATE_LABEL": "Gate",
        "DIVISION_LABEL": "Division",
        "MAINT_USER_LABEL": "Operator",
        "MODEL_NOT_USED": "Model is not used by any element.",
        "MODEL_NAME_REQUIRED": "Model name is required!",
        "MODEL_SERVICE_CYCLE_NUM": "Maintenance cycle must be a number!",
        "MODEL_POWER_NUM": "Rated power must be a number!",
        "MODEL_ADDED": "Model added!",
        "MODEL_DELETED": "Model deleted successfully!",
        "MODEL_NOT_FOUND": "Model not found!",
        "MODEL_CHECK_TITLE": "Model Check",
        "NEW_MODELS_HEADER": "[b]New Models (will be added):[/b]",
        "EXISTING_MODELS_DIFF_HEADER": "[b]Existing Models with Different Data:[/b]",
        "NO_ELEMENTS": "No elements",
        "NO_ELEMENTS_PAREN": "(No elements)",
        "NO_ELEMENTS_FOR_ITEM": "No elements registered for this item.",
        "NO_MODELS": "No models",
        "NO_INACTIVE_ELEMENTS": "No inactive elements in this substation",
        "ELEMENT_TYPES": [
            "HV Breaker",
            "MV Breaker",
            "Transformer 150/20KV",
            "Motor Drive",
            "Injection Transformer",
            "Current Transformer",
            "Voltage Transformer",
            "LT/MT Transformer (ATS)",
            "Disconnector",
            "Fused Disconnector",
            "Grounding Switch",
            "Capacitor Bank",
            "Node Resistor",
            "Lightning Arrester",
            "Battery Bank",
        ],
        "ELEMENT_BREAKER_YT": "HV Breaker",
        "ELEMENT_BREAKER_MT": "MV Breaker",
        "VIDAR_VACUUM_CHECK_LABEL": "VACUUM CHECK (VIDAR):",
        "VIDAR_LABEL_FB": "FB-FB:",
        "VIDAR_LABEL_FC": "FC-FC:",
        "VIDAR_HINT": "0.0",
        "VIDAR_SECTION_TITLE": "VIDAR Vacuum Check",
        "PHASE_TO_PHASE_LABEL": "FA-FA",
        "PHASE_TO_PHASE_LABEL_COLON": "FA-FA:",
        "INSULATION_RESISTANCE_CLOSED_TITLE": "Insulation Resistance - Breaker Closed (Ground)",
        "INSULATION_RESISTANCE_OPEN_TITLE": "Insulation Resistance - Breaker Open (Phase-Phase)",
        "INSULATION_PASSAGE_TITLE": "Passage Resistance (uOhm)",
        "INSULATION_MEASUREMENT_CLOSED_HEADER": "INSULATION RESISTANCE MEASUREMENT - BREAKER CLOSED (PH-GND):",
        "INSULATION_MEASUREMENT_OPEN_HEADER": "INSULATION RESISTANCE MEASUREMENT - BREAKER OPEN (PH-PH):",
        "INSULATION_PASSAGE_MEASUREMENT_CLOSED_HEADER": "PASSAGE RESISTANCE (uOhm) - BREAKER CLOSED:",
        "INSULATION_HINT": "0.0",
        "INSULATION_LABEL_FA_GND": "FA-GND",
        "INSULATION_LABEL_FB_GND": "FB-GND",
        "INSULATION_LABEL_FC_GND": "FC-GND",
        "INSULATION_LABEL_FA": "FA-FA",
        "INSULATION_LABEL_FB": "FB-FB",
        "INSULATION_LABEL_FC": "FC-FC",
        "ELEMENT_BREAKER_SUBSTR": "Breaker",
        "BREAKER_CATEGORIES_ALL": ["SF6", "Oil", "Low Oil"],
        "BREAKER_CATEGORIES_HV": ["SF6"],
        "BREAKER_CATEGORIES_MV": ["SF6", "Oil", "Low Oil"],
        "BREAKER_TYPES": ["Oil", "SF6", "Vacuum", "Gas Insulated"],
        "OPERATING_STATUS": ["Active", "Inactive"],
        "INSTALLATION_SPACE": ["Indoor", "Outdoor"],
        "VOLTAGE_LEVELS": ["(Nominal)", "150/20KV", "20KV", "150KV", "20KV/400V"],
        "VIEW_ELEMENT_TITLE": "View Element",
        "ELEMENTS_LIST_LABEL": "Elements maintained:",
        "PLEASE_SELECT_BREAKER_CATEGORY": "Please select breaker category!",
        "PLEASE_SELECT_EML": "Please select a .eml file!",
        "INACTIVE_ELEMENTS": "Inactive Elements ({count})",
        "ELEMENT_MAINT_HISTORY_TITLE": "Maintenance History - {element_name}",
        "NO_MAINTENANCE_HISTORY": "No maintenance history found for this element",
        "VIEW_FULL_MAINTENANCE": "Full Report",
        "EXPORT_MAINTENANCE_PDF": "Export PDF",
        "EXPORT_HISTORY_LIST_PDF": "Export List to PDF",
        "MAINTENANCE_DATE_LABEL": "Date:",
        "MAINTENANCE_TYPE_LABEL": "Type:",
        "ELEMENT_COMMENTS_LABEL": "Element Comments:",
        "ELEMENT_ADDED": "Element added to {substation_name}!",
        "ELEMENT_DUPLICATE": "An element with this name already exists in this substation!",
        "VIEW_ACTIVE_ELEMENTS": "View active elements ({count})",
        "FILTER_TYPE": "Type filter:",
        "FILTER_GATE": "Gate filter:",
        "FILTER_SUBSTATION": "Substation filter:",
        "LOC": "Location",
        "ADOPTION": "Adoption",
        "INFO": "Details",
        "GATES": "Gates",
        "CAPACITORS": "Capacitors",
        "MAINTENANCES": "Maintenances",
        "LAST": "Last",
        "SINGLE_LINE": "Single-line",
        "MONTHS": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
        ],
        "DAYS": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
        ],
        "BREAKER_LABEL_CENTRAL": "Central",
        "BREAKER_LABEL_INTERCON": "Interconnection",
        "BREAKER_LABEL_CAPACITOR": "Capacitor Bank",
        "BREAKER_LABEL_LINE": "Line",
        "GATE_PREFIX": "Gate",
        "ALL_LABEL": "(All)",
        "DIVISION_DEFAULT": "Div",
        "PICKER_EMPTY_SELECTION": "Picker returned empty selection (None).",
        "ANDROID_FILECHOOSER_FALLBACK": "Android file chooser is not available. Use the file list in the window.",
        "FILECHOOSER_NOT_AVAILABLE": "File chooser is not available",
        "FILECHOOSER_ANDROID_ONLY": "File chooser is available only on Android.",
        "FILECHOOSER_INTERNAL_ERROR": "File chooser internal error.",
        "FILECHOICE_CANCELLED": "File choice failed or was canceled.",
        "MODE_LABEL_LOCAL": "Source: Local Database",
        "LOCAL_DB_BUTTON": "Database",
        "CHANGELOG_BUTTON": "Change-log",
        "CHANGELOG_RECORDED": "Change recorded in the change log.",
        "ADOPTION_DATE_LABEL": "Adoption Date:",
        "NAME_REQUIRED": "Name is required",
        "ELEMENT_TYPE_LABEL": "Element Type:",
        "RETRY": "Retry",
        "COPYING_FILE": "Copying file...",
        "COPYING_FILE_MSG": "Copying file from filesystem. Please wait...",
        "OVERALL_COMMENTS_HINT": "General maintenance comments...",
        "GOOGLE_MAPS_LINK": "Google Maps Link",
        "SHARE_BUTTON": "Share",
        "SUMMARY_BUTTON": "Summary",
        "LATER_BUTTON": "Later",
        "CHANGE_LOG_SUMMARY_TITLE": "Change log summary",
        "CHANGE_LOG_EMPTY": "The change log is empty.",
        "CHANGE_LOG_NO_MAJOR_ISSUES": "no significant findings",
        "CHANGE_LOG_PENDING_REVIEW_TITLE": "Pending changes",
        "CHANGE_LOG_PENDING_REVIEW": "The change log contains pending changes.",
        "CHANGE_LOG_PENDING_REVIEW_STARTUP": "The change log contains pending changes from a previous session.",
        "CHANGE_LOG_PENDING_REVIEW_AFTER_SHARE": "Sharing was launched. Do you want to clear the change log now?",
        "COPY_PATH": "Copy path",
        "LOADING_ELEMENTS": "Loading elements...",
        "RETRY_LOAD": "Retry loading",
        "ELEM_COMMENTS_HINT": "Comments for this element...",
        "SHOW_DB_BUTTON": "View substations database",
        "IMPORT_BUTTON": "Import/Export Data",
        "MAINTENANCE_BUTTON": "Maintenances",
        "INSPECTION_BUTTON": "Inspections",
        "ISOLATION_BUTTON": "Isolation Requests",
        "SF6_BUTTON": "SF6",
        "MODELS_BUTTON": "Manage Element Types",
        "PEOPLE_BUTTON": "Manage Staff",
        "TOOLTIP_EDIT": "Edit",
        "TOOLTIP_DELETE": "Delete",
        "TOOLTIP_VIEW": "View",
        "TOOLTIP_MAINTENANCE": "Maintenance",
        "TOOLTIP_INSPECTION": "Inspection",
        "TOOLTIP_MANUAL": "Manual",
        "VIEW_SHORT": "View",
        "PDF_BUTTON": "PDF",
        "VIEW_PROMPT": "Select what you want to view:",
        "SEARCH_HINT": "Search (name/date)",
        "PREVIOUS": "Previous",
        "NEXT": "Next",
        "LOAD_MORE": "Load more",
        "PAGE_LABEL_TEMPLATE": "Page {page}",
        "ALL_SUBSTATIONS_LABEL": "All substations",
        "VIEW_SELECTION_TITLE": "View Selection",
        "SORT_OPTIONS": [
            "Date (desc)",
            "Date (asc)",
            "Substation A-Z",
        ],
        "PAGE_SIZE_LABEL": "Items per page",
        "PAGE_SIZE_OPTIONS": ["10", "20", "30", "50"],
        "SELECT_PROMPT": "Select",
        "SHOW_ALL_SUBSTATIONS": "View All Substations",
        "SELECT_ALL_BTN": "Select All",
        "ADD_MENU_TITLE": "Add substations and elements",
        "ADD_SUBSTATION_BTN": "Add New Substation",
        "ADD_ELEMENT_BTN": "Add New Element",
        "ADD_ELEMENTS_TITLE": "Add elements",
        "ADD_SUBSTATION_TITLE": "Add Substation",
        "ADD_ELEMENT_TITLE": "Add Element",
        "ADD_MODEL_TITLE": "Add New Model",
        "ADD_MANUAL": "Add Manual",
        "ADD_ELEMENTS_PROMPT": "Add elements for the new substation before continuing:",
        "CONTINUE": "Continue",
        "OPEN_LOCAL_DB_TITLE": "Open Local Database",
        "OPEN_FOLDER": "Open folder",
        "CONFIRM_DELETE_TITLE": "Delete Confirmation",
        "DUPLICATE_OPTIONS_INCOMPLETE": (
            "Complete the choices for all duplicates or use 'Replace All' / 'Skip All'."
        ),
        "RESPONSIBLE_NOT_FOUND_TITLE": "Responsible not found",
        "FORM_NUMBER": "Form No.:",
        "FORM_NUMBER_HINT": "Form No.",
        "ELEMENT_NAME_LABEL": "Element Name",
        "ELEMENT_NAME_HINT": "Element Name",
        "SERIAL_NUMBER_LABEL": "Serial Number",
        "SERIAL_NUMBER_HINT": "Serial Number",
        "ELEMENT_MANUFACTURE_YEAR_LABEL": "Manufacture Year",
        "ELEMENT_MANUFACTURE_YEAR_HINT": "YYYY",
        "MAINTENANCE_DATE_HINT": "YYYY-MM-DD",
        "MANUFACTURER_LABEL": "Manufacturer",
        "MANUFACTURER_HINT": "Manufacturer",
        "MODEL_LABEL": "Model",
        "MODEL_HINT": "Model",
        "MODEL_VERSION_LABEL": "Model Version",
        "MODEL_VERSION_HINT": "Version",
        "INSTALLATION_SPACE_LABEL": "Installation Space",
        "OPERATING_STATUS_LABEL": "Operating Status",
        "MAINTENANCE_CYCLE_LABEL": "Maintenance Cycle",
        "MAINTENANCE_CYCLE_HINT": "Number",
        "DATE_LABEL": "Date:",
        "DATE_HINT": "YYYY-MM-DD",
        "REGION_LABEL": "Region:",
        "REGION_HINT": "Region",
        "INSPECTOR_LABEL": "Inspector Name:",
        "MONTH_LABEL": "Month:",
        "DAY_LABEL": "Day:",
        "YEAR_LABEL": "Year:",
        "OBSERVATIONS_HINT": "Observations",
        "EMAIL_RECIPIENTS_MISSING": (
            "No email recipients. Add recipients from Staff Management."
        ),
        "MAINTENANCE_HEADER": "Maintenance: {name}",
        "PEOPLE_SUMMARY": "Responsible: {resp} | Crew: {crew}",
        "COMMENTS_LABEL": "Comments: {text}",
        "MAINTENANCE_COMMENTS_SECTION": "Maintenance Comments",
        "ELEMENT_COMMENTS_SECTION": "Element Comments",
        "MAINT_LAST_LABEL": "Last Maintenance: {date}",
        "INVALID_DATE_FORMAT": "Invalid date format! Use: YYYY-MM-DD HH:MM",
        "END_BEFORE_START": "End date must be after start!",
        "ERROR_DURING_CHECK_PREFIX": "Error during check: ",
        "RECORD_NOT_FOUND": "Record not found.",
        "TEMPLATE_SUBSTATIONS_TITLE": "Substations Template",
        "TEMPLATE_ELEMENTS_TITLE": "Elements Template",
        "OPENPYXL_MISSING": "openpyxl is not installed!",
        "TEMPLATE_SUBSTATIONS_HEADERS": ["Name", "Location", "Adoption Date"],
        "TEMPLATE_ELEMENTS_HEADERS": [
            "Substation Name",
            "Element Type",
            "Name",
            "Serial Number",
            "Maintenance Date",
            "Breaker Type",
            "Breaker Role",
            "Operating Status",
            "Gate",
            "Model Name",
            "Model Manufacturer",
            "Model Installation Space",
        ],
        "ITEM_DELETED": "Element deleted!",
        "MAINTENANCE_UPDATED": "Maintenance updated!",
        "MAINTENANCE_CREATED": "Maintenance created!",
        "CHANGES_SAVED": "Changes saved!",
        "CONFIRM_DELETE_SUBSTATION_FMT": (
            "Are you sure you want to delete\n"
            'substation "{substation_name}"\n'
            "and ALL its elements?"
        ),
        "CONFIRM_DELETE_MAINT_FMT": "Are you sure you want to delete\nthis maintenance?",
        "UNREGISTERED_PLACEHOLDER": "(Unregistered)",
        "EMPTY_PLACEHOLDER": "(Empty)",
        "MODEL_SELECT_PROMPT": "Select model",
        "BREAKER_TYPE_LABEL": "Breaker Type:",
        "BREAKER_CATEGORY_LABEL": "Breaker Category:",
        "RATED_POWER_HINT": "e.g. 50",
        "SETTINGS_TOOLTIP": "Settings",
        "LANGUAGE_LABEL": "Language:",
        "LANGUAGE_OPTION_EL": "Greek",
        "LANGUAGE_OPTION_EN": "English",
        "LANGUAGE_SAVED_RESTART": "Language saved. The app will restart now.",
        # --- Database Path ---
        "DB_PATH_LABEL": "Database Path:",
        "DB_PATH_BUTTON": "Change",
        "DB_PATH_SAVED_RESTART": "Database path saved. The app will restart now.",
        "DB_PATH_DEFAULT": "(Default)",
        "DB_PATH_SELECT": "Select database file",
        "DB_FILE_NOT_FOUND": "Database file not found!",
        "DB_FILE_INVALID": "Invalid database file!",
        "SYNC_SETTINGS_LABEL": "Sync / Backup Settings:",
        "SYNC_SETTINGS_HELP_BUTTON": "Sync Settings Help",
        "SYNC_SETTINGS_HELP_TEXT": (
            "OneDrive sync (multi-user collaboration):\n"
            "1) User A creates a shared OneDrive folder and shares it with the team.\n"
            "2) Each user syncs this folder locally using OneDrive Desktop.\n"
            "3) Set sync_root_path to your LOCAL OneDrive path "
            "(e.g. C:\\Users\\...\\OneDrive\\Shared).\n"
            "4) You can use an existing folder - no need to create a new one.\n"
            "5) OneDrive automatically syncs changes between all users in the background.\n"
            "6) The app creates required subfolders automatically."
        ),
        "SYNC_AUTO_ENABLED_LABEL": "Auto sync:",
        "STARTUP_SYNC_PROBE_ENABLED_LABEL": "Check differences at startup (startup probe):",
        "STARTUP_SYNC_PROMPT_ON_CHANGE_LABEL": (
            "Prompt before syncing when differences are found:"
        ),
        "STARTUP_SYNC_CHANGES_TITLE": "What changed since the last startup:",
        "SYNC_INTERVAL_MINUTES_LABEL": "Auto sync interval (minutes):",
        "SYNC_BACKUP_ON_CHANGE_LABEL": (
            "Create snapshot when new accepted changes exist:"
        ),
        "SYNC_HOT_KEEP_LABEL": "Hot backup snapshots to keep:",
        "SYNC_RETENTION_ENABLED_LABEL": "Auto-delete old sync files:",
        "SYNC_RETENTION_DAYS_LABEL": "Keep sync files for (days):",
        "SYNC_RETENTION_DAYS_INVALID": "Invalid sync retention days value.",
        "SYNC_ROOT_PATH_LABEL": "Sync root folder (sync_root_path):",
        "SYNC_ROOT_PATH_HINT": "Empty = default (next to DB: sync_exchange)",
        "BACKUP_ROOT_PATH_LABEL": "Backup root folder (backup_root_path):",
        "BACKUP_ROOT_PATH_HINT": "Empty = default (next to DB: backups_auto)",
        "SYNC_INTERVAL_INVALID": "Invalid auto-sync minutes value.",
        "SYNC_HOT_KEEP_INVALID": "Invalid hot snapshot count value.",
        "SYNC_MANUAL_SUMMARY_FMT": (
            "Inbox processing completed.\n"
            "Processed: {processed}\n"
            "Accepted: {accepted}\n"
            "Conflicts: {conflicts}\n"
            "Rejected: {rejected}"
        ),
        "SYNC_SNAPSHOT_LINE_FMT": "Snapshot: {snapshot}",
        "SYNC_AUTO_SUMMARY": (
            "Automatic sync completed:\n"
            "✓ Accepted: {accepted}\n"
            "⚠ Conflicts: {conflicts}\n"
            "❌ Rejected: {rejected}"
        ),
        "SYNC_BACKUP_CREATED": "Backup created.",
        "SYNC_ISSUES_FOUND": (
            "Found previous changes with issues:\n"
            "• Rejected: {rejected}\n"
            "• Conflicts: {conflicts}"
        ),
        "SYNC_ISSUES_ACTION": "Check rejected and conflicts folders in sync_root.",
        "SYNC_ONEDRIVE_BUTTON": "OneDrive Sync",
        "IMPORT_SYNC_INBOX_BUTTON": "Sync with OneDrive",
        "CHANGES_EXPORTED_FMT": "Exported {count} changes to file:\n{file}",
        "SYNC_EXPORTED_CHANGES_LINE_FMT": "Outgoing changes: {count} (file: {file})",
        "CHANGES_EXPORT_ERROR": "Error exporting changes: ",
        "EXPORT_CHANGES_BUTTON": "Export Changes Now",
        "EXPORT_CHANGES_ERROR_FMT": "Export error: {error}",
        "NO_PENDING_CHANGES": "No pending changes to export.",
        "SYNC_BUTTON": "Sync",
        "SYNCING": "Syncing...",
        "SYNC_ERROR": "Sync error occurred",
        "SETTINGS_SAVED": "Settings saved!",
        "NO_DB": "No database loaded",
        # --- Login / User Session ---
        "LOGIN_TITLE": "User Login",
        "LOGIN_PROMPT": "Select your name to login:",
        "LOGIN_SUCCESS_FMT": "Welcome, {name}!",
        "USER_LABEL": "User:",
        "LOGGED_IN_AS_FMT": "Logged in as: {name} ({role})",
        "NO_USER_LOGGED_IN": "No user logged in",
        "LOGOUT_CONFIRM": "Do you want to logout?",
        "LOGIN_REQUIRED": "You must login to use the application.",
        "FILE_DIALOG_SELECT_TITLE": "Select file",
        "FILE_DIALOG_SAVE_TITLE": "Save file",
        "FILE_DIALOG_ALL_FILES": "All files",
        "FILE_DIALOG_EXCEL_FILES": "Excel files",
        "FILE_DIALOG_CSV_FILES": "CSV files",
        "FILE_DIALOG_JSON_FILES": "JSON files",
        "FILE_DIALOG_ANDROID_CHANGELOG_FILES": "Android change log files",
        "SF6_MANAGEMENT_TITLE": "SF6 Management",
        "PRINT": "Print",
        "EXCEL": "Excel",
        "ELEMENT_LABEL": "Element",
        "LEAKAGE_LABEL": "Leakage (kg)",
        "NO_LEAK_ENTRIES": "No leakage entries for the year.",
        "PDF_CREATED": "PDF created:\n{path}",
        "PDF_CREATE_FAILED": "Failed to create PDF:\n{err}",
        "EXCEL_CREATED": "Excel created:\n{path}",
        "EXCEL_CREATE_FAILED": "Failed to create Excel:\n{err}",
        "PDF_CREATED_TITLE": "PDF Created",
        "PDF_ELEMENT_CREATED_FMT": (
            'The PDF file for element "{element_name}"\n'
            "was created successfully!\n\n"
            "Saved to:\n{pdf_path}"
        ),
        "OPEN_FILE_NOT_FOUND": "File not found!",
        "OPEN_FILE_ERROR_TITLE": "Error",
        "OPEN_FILE_ERROR_PREFIX": "Failed to open file:\n",
        "OPENPYXL_MISSING_EXCEL_EXPORT": (
            "openpyxl package not found. Install it for Excel export."
        ),
        "SF6_SUMMARY_FMT": (
            "Installed SF6 (active): {installed_sf6:.2f} kg | "
            "Active SF6 elements: {active_elements} | "
            "Substations with SF6: {active_substations}\n"
            "Year: {year_value} | Leakages: {total_leakage:.2f} kg | "
            "Percentage: {percentage:.2f}%"
        ),
        "SF6_SUMMARY_SHEET_TITLE": "Summary",
        "SF6_SUMMARY_TOTAL_INSTALLED": "TOTAL INSTALLED AMOUNT (kg)",
        "SF6_SUMMARY_LEAKS_YEAR_FMT": "LEAKAGES {year} (kg)",
        "SF6_SUMMARY_PERCENT_YEAR_FMT": "LEAKAGE PERCENT {year}",
        "SF6_SUBSTATION_HEADER": "Substation",
        "SF6_TOTAL_LEAKAGE_HEADER": "Total Leakages (kg)",
        "SF6_TABLE_TITLE": "TABLE 4: EMISSIONS SOURCE FROM SF6 EQUIPMENT",
        "SF6_TABLE_HEADERS": [
            "No.",
            "BOK or Region",
            "Facility (e.g., Substation Name)",
            "Measurement Unit",
            "Filling or Replacement (Methodology)",
            "TOTAL INSTALLED AMOUNT (kg)",
            "LEAKAGE AMOUNT (kg)",
            "DATE",
            "CREW RESPONSIBLE",
            "SIGNATURE",
        ],
        "ORG_SHORT": "HEDNO",
        "TEMPLATE_SUBSTATIONS_EXAMPLES": [
            ("Substation A", "https://maps.google.com/?q=example1", "2025-01-15"),
            ("Substation B", "https://maps.google.com/?q=example2", "2025-01-20"),
        ],
        "TEMPLATE_ELEMENTS_EXAMPLES": [
            (
                "Substation A",
                "Διακόπτης ΜΤ",
                "Main Breaker",
                "SN-001",
                "2025-01-20",
                "SF6",
                "Κεντρικός",
                "Ενεργή",
                "ΠΥΛΗ 1",
                "SF6-400",
                "ABB",
                "Εσωτερικού",
            ),
            (
                "Substation A",
                "Μετασχηματιστής 150/20KV",
                "Transformer 1",
                "SN-002",
                "2025-01-18",
                "",
                "",
                "Ενεργή",
                "ΠΥΛΗ 1",
                "GEAFOL",
                "Siemens",
                "Εξωτερικού",
            ),
        ],
        "ERROR_FMT": "Error: {exc}",
    },
}
