"""Centralized UI strings to avoid hardcoded literals in code.

STRINGS is a nested dict grouping labels, button texts, popup titles and
common messages. Keys are organized by category to make navigation easier.
When adding new strings, place them under the most appropriate category.
"""

STRINGS = {
    # Top-level button text used in many places
    "BUTTONS": {
        "IMPORT": "Εισαγωγή",
        "ADD": "Προσθήκη",
        "VIEW": "Δες",
        "REFRESH": "Ανανέωση",
        "OPEN": "Άνοιγμα",
        "REPLACE": "Αντικατάσταση",
        "SKIP": "Παράλειψη",
        "REPLACE_ALL": "Αντικατάσταση Όλων",
        "SKIP_ALL": "Παράλειψη Όλων",
        "CONFIRM": "Επιβεβαίωση",
        "EDIT": "Επεξεργασία",
        "LIST": "Λίστα",
        "CANCEL": "Ακύρωση",
        "EMAIL": "Email",
        "APPLY": "Εφαρμογή",
        "BACKUP_APPLY": "Backup & Εφαρμογή",
        "CLOSE": "Κλείσιμο",
        "INSPECTIONS": "Επιθεωρήσεις",
        "SAVE": "Αποθήκευση",
        "BACK": "Πίσω",
        "MAINTENANCE": "Συντήρηση",
        "INSPECT": "Επιθεώρηση",
        "DELETE": "Διαγραφή",
        "UPDATE": "Ενημέρωση",
        "YES": "Ναι",
        "NO": "Όχι",
        "COPY": "Αντιγραφή",
        "BROWSE_FILE": "Αναζήτηση αρχείου",
        "ADD_MAINTENANCE": "+ Προσθήκη Νέας Συντήρησης",
        "ADD_MODEL": "+ Προσθήκη Νέου Μοντέλου",
    },

    # Common window / popup titles
    "TITLES": {
        "ERROR": "Σφάλμα",
        "SUCCESS": "Επιτυχία",
        "INFO": "Πληροφορία",
        "IMPORT_MENU": "Εισαγωγή από αρχείο",
        "IMPORT_ANDROID": "Εισαγωγή αλλαγών από Android",
        "PREVIEW_CHANGELOG": "Προεπισκόπηση αλλαγών",
        "INSPECTION_ENTRY": "Καταχώρηση Επιθεώρησης",
        "INSPECTION_HISTORY": "Ιστορικό Επιθεώρησης",
        "INSPECTION_DETAILS": "Λεπτομέρειες Επιθεώρησης",
        "IMPORT_SUBSTATIONS_TITLE": "Εισαγωγή Υποσταθμών",
    },

    # Application-wide messages grouped by functional area
    "MESSAGES": {
        # --- General / Application info ---
        "APP_TITLE": "Υποσταθμοί ΔΕΔΔΗΕ ΔΕΕΔ/ΚΣΜΘ/ΤΕΙ",
        "APP_INFO_SHORT": "Πληρ. Εφαρμ.",
        "APP_INFO_TITLE": "Πληροφορίες Εφαρμογής",
        "APP_INFO_BODY": (
            "Υποσταθμοί ΔΕΔΔΗΕ ΔΕΕΔ/ΚΣΜΘ/ΤΕΙ\n"
            "Έκδοση: {version}\n\n"
            "Λειτουργίες εφαρμογής:\n"
            "• Προβολή και διαχείριση βάσης υποσταθμών\n"
            "• Προσθήκη/επεξεργασία/διαγραφή υποσταθμών και στοιχείων\n"
            "• Κατηγορίες διακοπτών (SF6/Ελαίου/Πτωχού Ελαίου)\n"
            "• Διαχείριση τύπων στοιχείων (μοντέλα/κατασκευαστές/κύκλοι)\n"
            "• Καταχώρηση συντηρήσεων\n"
            "• Εισαγωγή συντήρησης από e-mail (.eml)\n"
            "• Ιστορικό συντηρήσεων (όλων/ανά υποσταθμό)\n"
            "• Μετρήσεις διακοπτών (μόνωση/διέλευση/χειρισμοί)\n"
            "• Ποιότητα αερίου SF6 & διαρροές (kg)\n"
            "• Διαχείριση SF6 (αναφορά διαρροών ανά έτος)\n"
            "• Εξαγωγή Excel αναφορών SF6 (σύνοψη & ανά υποσταθμό)\n"
            "• Εκτύπωση PDF αναφορών συντήρησης\n"
            "• Επιθεωρήσεις (καταχώρηση/προβολή/ιστορικό)\n"
            "• Αιτήσεις απομόνωσης\n"
            "• Εισαγωγή υποσταθμών/στοιχείων από CSV/Excel\n"
            "• Αναφορές PDF & Excel\n\n"
            "Φάκελος εφαρμογής: {app_dir}"
        ),
        "LOADING": "Φόρτωση...",
        "COPY": "Αντιγραφή",
        "DASH": "-",

        # --- Files / Import / PDF ---
        "ENTER_PATH": "Παρακαλώ εισάγετε διαδρομή ή επιλέξτε αρχείο!",
        "FILE_PATH_LABEL": "Διαδρομή αρχείου:",
        "FILE_PATH_HINT": "Διαδρομή αρχείου",
        "FILE_NOT_FOUND": "Το αρχείο δεν βρέθηκε!",
        "PLEASE_SELECT_PDF": "Παρακαλώ επιλέξτε αρχείο PDF!",
        "UNSUPPORTED_FILE_FORMAT": "Μη υποστηριζόμενη μορφή αρχείου",
        "FILE_HAS_NO_DATA": "Το αρχείο δεν περιέχει δεδομένα.",
        "IMPORT_FAILED": "Αποτυχία εισαγωγής:",
        "IMPORT_SUCCESS": "Επιτυχής εισαγωγή.",
        "SELECT_MONOGRAM_PDF_TITLE": "Επιλογή Μονογραμμικού PDF",
        "CHANGELOG_FILE_LABEL": "Διαδρομή αρχείου change log (.jsonl):",

        # --- Substations / DB ---
        "NO_SUBSTATIONS": "Δεν υπάρχουν υποσταθμοί!",
        "EMPTY_DB": "Κενή βάση",
        "ADD_NEW_SUBSTATION_PROMPT": "Ή προσθέστε νέο υποσταθμό:",
        "PLEASE_SELECT_OR_ADD_SUBSTATION": "Παρακαλώ επιλέξτε υποσταθμό ή προσθέστε νέο.",
        "ENTER_SUBSTATION_NAME": "Παρακαλώ εισάγετε όνομα υποσταθμού!",
        "SUBSTATION_LABEL": "Υποσταθμός:",
        "SUBSTATION_NAME_LABEL": "Όνομα Υποσταθμού:",
        "SUBSTATION_NAME_HINT": "Όνομα Υποσταθμού",
        "SUBSTATION_NEW_HINT": "Όνομα νέου υποσταθμού",
        "SUBSTATION_IS_THESSALONIKI": "Υ/Σ Θεσσαλονίκης",
        "SUBSTATION_ADDED": "Υποσταθμός προστέθηκε!",
        "SUBSTATION_EXISTS": "Ο υποσταθμός υπάρχει ήδη.",
        "SELECT_SUBSTATION": "Επιλογή Υποσταθμού:",
        "SELECT_SUBSTATION_BTN": "Επιλογή Υποσταθμού",
        "PROMPT_SUBSTATION_NOT_FOUND_TITLE": "Ο υποσταθμός δε βρέθηκε",
        "PROMPT_SUBSTATION_SELECT": "Επιλέξτε υποσταθμό για την εισαγωγή:",
        "SUBSTATION_NOT_FOUND": "Δεν βρέθηκε υποσταθμός.",
        "MISSING_SUBSTATIONS_WILL_CREATE": "Οι παρακάτω υποσταθμοί δεν υπάρχουν και θα δημιουργηθούν:",
        "NEW_SUBSTATIONS_TITLE": "Νέοι Υποσταθμοί Εντοπίστηκαν",

        # --- Maintenance / Records ---
        "MAINTENANCE_SAVED_CHANGELOG": "Η συντήρηση καταχωρήθηκε στο change log.",
        "MAINTENANCE_DELETED": "Η συντήρηση διαγράφηκε!",
        "MAINTENANCE_NOT_FOUND": "Δεν βρέθηκε η συντήρηση.",
        "NO_MAINTENANCES": "Δεν υπάρχουν καταχωρημένες συντηρήσεις",
        "NO_MAINT_FOR_SUBSTATION": (
            'Δεν υπάρχουν καταχωρημένες συντηρήσεις για τον υποσταθμό "{substation_name}".\n'
            "Χρησιμοποιήστε το κουμπί παραπάνω για να προσθέσετε."
        ),
        "MAINT_HISTORY_LABEL": "Ιστορικό Συντήρησης",
        "MAINTENANCE_NAME_FMT": "Υ/Σ {substation_name} - {date}",
        "NO_RECORD_ELEMENTS": "Δεν υπάρχουν στοιχεία για αυτή τη συντήρηση.",

        # --- Maintenance form labels & validation ---
        "DATE_TIME_LABEL": "Ημερομηνία & Ώρα:",
        "DATE_REQUIRED": "Η ημερομηνία είναι υποχρεωτική!",
        "DATE_PREFIX": "Ημ/νία:",
        "MAINT_TYPE_LABEL": "Τύπος Συντήρησης:",
        "MAINTENANCE_TYPES": ["Επαναληπτική συντήρηση", "Βλάβη", "Οπτικός έλεγχος"],
        "MAINT_TYPE_DEFAULT": "Επαναληπτική συντήρηση",
        "RESPONSIBLE_LABEL": "Υπεύθυνος Συντήρησης (υποχρεωτικό):",
        "RESPONSIBLE_REQUIRED": "Ο υπεύθυνος συντήρησης είναι υποχρεωτικός!",
        "CREW_LABEL": "Ομάδα Συντήρησης (προαιρετικό):",
        "OVERALL_COMMENTS_LABEL": "Γενικά Σχόλια Συντήρησης:",
        "ELEMENTS_SECTION_LABEL": "Στοιχεία που συντηρήθηκαν (τουλάχιστον 1):",
        "NO_ELEMENTS_IN_SUBSTATION": "Δεν υπάρχουν στοιχεία σε αυτόν τον υποσταθμό",
        "SELECT_AT_LEAST_ONE_ELEMENT": "Πρέπει να επιλέξετε τουλάχιστον ένα στοιχείο!",
        "ADD_ELEMENT_BEFORE_CONTINUE": "Προσθέστε τουλάχιστον ένα στοιχείο πριν τη συνέχεια.",

        # --- Inspections ---
        "INSPECTION_SAVED": "Η επιθεώρηση καταχωρήθηκε!",
        # The inspection rows were reviewed for typos and corrected where obvious.
        "INSPECTION_ROWS": [
            "Έλεγχος εξωτερικών & εσωτερικών θυρών ΥΣ",
            "Έλεγχος εσωτερικού χώρου κτηρίου (φωτισμός, κλιματισμός κλπ)",
            "Έλεγχος περιβάλλοντος χώρου (βλάστηση, δένδρα, φωτισμός κλπ)",
            "Έλεγχος μέσων πυρόσβεσης γενικά",
            "Οπτικός έλεγχος διαρροής/στάθμης/θερμοκρασίας λαδιού, silica gel στον Μ/Σ",
            "Οπτικός έλεγχος διαρροής λαδιού ή πίεσης SF6 ή πίεσης αέρα στους διακόπτες ισχύος 150kV & 20kV",
            "Έλεγχος λειτουργίας ανεμιστήρων Μ/Σ",
            "Οπτικός έλεγχος Μ/Σ έγχυσης, ΜΣΕ, ΜΣΤ, Μ/Σ εσωτερικής υπηρεσίας, αντίστασης κόμβου (θερμοκρασία)",
            "Οπτικός έλεγχος μονωτήρων (ρύπανση, εκδορές κ.α.)",
            "Οπτικός έλεγχος τηκτών πυκνωτών",
            "Έλεγχος σημάνσεων στους πίνακες Μ/Σ, Α/Δ 150kV & 20kV",
            "Λήψη φωτογραφίας όταν απαιτείται",
            "Οπτικός έλεγχος των πυλών, A/Z και γενικά του ικριώματος για τυχόν φωλιές από πτηνά, σπασίματα, μονωτήρες, κλαδιά, σύρματα κλπ",
            "Οπτικός έλεγχος στους πίνακες διακοπτών 20kV (αναγγελίες, ενδείξεις οργάνων, πόρτες) και έλεγχος θορύβων, ιονισμών",
            "Έλεγχοι υγρασίας (υπόγειο, κανάλια καλωδίων), αφυγραντήρων, θερμαντικών, φορητών πυροσβεστήρων",
            "Έλεγχος φορτιστή 110V οπτικά με έλεγχο της τάσης, έντασης και καταγραφή",
            "Έλεγχος για alarm έλλειψης DC στον γενικό πίνακα DC",
            "Οπτικός έλεγχος διαρροών στοιχείων συσσωρευτών",
            "Οπτικός έλεγχος των ΑΠ/Ζ και των 'γεφυρών' αυτών στον 1ο στύλο κάθε γραμμής (σπασμένοι ΑΠ/Ζ, μονωτήρες, εκτονωμένα Α/Ξ κλπ)",
            "Έλεγχος λειτουργίας ψηφιακού συστήματος (χειρισμοί, ενδείξεις, σημάνσεις)",
            "Τροφοδοσία υπολογιστή",
            "Απόψεις και τυχόν προτάσεις για την καλύτερη λειτουργία τόσο του εξοπλισμού, όσο και του κτηρίου γενικά του Υ/Σ",
        ],
        "INSPECTION_SECTION_2": "[b]Έλεγχος Χώρων ΥΣ[/b]",
        "INSPECTION_SECTION_3": "[b]Μ/Σ 150/20kV & Διακόπτες 150kV & 20kV[/b]",
        "INSPECTION_SECTION_3A": "[b]Υπαίθριες πύλες 20 kV[/b]",
        "INSPECTION_SECTION_3B": "[b]Υπαίθριες πύλες 20 kV[/b]",
        "INSPECTION_SECTION_4": "[b]Κτίριο χειρισμών & Τ.Α.Σ.[/b]",
        "INSPECTION_SECTION_5": "[b]Αποζεύκτες Γραμμών[/b]",
        "INSPECTION_SECTION_6": "[b]PC Χειρισμών[/b]",
        "INSPECTION_SECTION_7": "[b]Απόψεις[/b]",
        # Additional inspection UI messages
        "INSPECTION_BASE_FIELDS": [
            "Υποσταθμός",
            "Αρ. Δελτίου",
            "Μήνας",
            "Ονομ. Επιθεωρητή",
            "Περιοχή",
            "Ημέρα",
            "Έτος",
            "Ημερομηνία",
        ],
        "IMPORT_INSPECTIONS_TITLE": "Εισαγωγή Επιθεωρήσεων",
        "IMPORT_INSPECTIONS_DONE": "Ολοκληρώθηκε η εισαγωγή ({inserted} εγγραφές).",
        "IMPORT_INSPECTIONS_DIALOG": "Εισαγωγή επιθεωρήσεων από αρχείο",
        "NO_INSPECTIONS": "Δεν υπάρχουν καταχωρημένες επιθεωρήσεις. Θέλετε να δημιουργήσετε μία;",
        "INSPECTION_COUNT_FMT": "{count} εγγραφές επιθεώρησης",
        "SUBSTATION_INSPECTION_HISTORY_TITLE_FMT": "Ιστορικό Επιθεωρήσεων - {substation_name}",
        "SUBSTATION_INSPECTION_COUNT_FMT": "{count} εγγραφές επιθεώρησης για τον υποσταθμό {substation_name}",
        "SUBSTATION_LABEL_PLAIN": "Υποσταθμός",
        "DATE_PLAIN": "Ημερομηνία",
        "MEASUREMENT_RESISTANCE_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ (Ω)",

        # --- People / Staff ---
        "NO_PEOPLE": "Δεν υπάρχουν καταχωρημένα άτομα. Παρακαλώ προσθέστε προσωπικό.",
        "SURNAME_LABEL": "Επώνυμο:",
        "NAME_LABEL": "Όνομα:",
        "ROLE_LABEL": "Ρόλος:",
        "EMAIL_LABEL": "Email:",
        "EMAIL_RECIPIENT_LABEL": "Παραλήπτες αναφοράς email",
        "ACTIVE_LABEL": "Ενεργός",
        "STAFF_LOAD_FAILED": "Ανεπιτυχής φόρτωση διαχείρισης προσωπικού.",
        "PERSON_NOT_FOUND": "Το άτομο δεν βρέθηκε!",
        "EDIT_PERSON_TITLE": "Επεξεργασία Προσώπου",
        "SURNAME_ROLE_REQUIRED": "Το επώνυμο και ο ρόλος είναι υποχρεωτικά!",
        "PERSON_IN_USE": "Το άτομο έχει χρησιμοποιηθεί σε συντηρήσεις. Διαγράψτε το μόνο αφού αφαιρεθεί από το ιστορικό ή απενεργοποιήστε το.",
        "CONFIRM_DELETE_PERSON_FMT": "Είστε σίγουροι ότι θέλετε να διαγράψετε\nτο άτομο \"{person_name}\";",

        # Missing messages added during DBrun.py sweep
        "NO_AVAILABLE_RESPONSIBLE": "Δεν υπάρχει διαθέσιμος υπεύθυνος συντήρησης με τα κατάλληλα δικαιώματα. Προσθέστε ή ενημερώστε προσωπικό.",
        "SF6_LEAK_METHODOLOGY_REQUIRED": "Για διαρροή SF6 απαιτείται συμπλήρωση μεθοδολογίας (Πλήρωση/Αντικατάσταση).",
        "GATE_LABEL": "Πύλη",
        "DIVISION_LABEL": "Τομέας",
        "MAINT_USER_LABEL": "Χειριστής",
        # --- Models / Element types ---
        "MODEL_NOT_USED": "Το μοντέλο δεν χρησιμοποιείται σε κανένα στοιχείο.",
        "MODEL_NAME_REQUIRED": "Το όνομα μοντέλου είναι υποχρεωτικό!",
        "MODEL_SERVICE_CYCLE_NUM": "Ο κύκλος συντήρησης πρέπει να είναι αριθμός!",
        "MODEL_POWER_NUM": "Η ονομαστική ισχύς πρέπει να είναι αριθμός!",
        "MODEL_ADDED": "Το μοντέλο προστέθηκε!",
        "MODEL_DELETED": "Το μοντέλο διαγράφηκε επιτυχώς!",
        "MODEL_NOT_FOUND": "Το μοντέλο δεν βρέθηκε!",
        "MODEL_CHECK_TITLE": "Έλεγχος Μοντέλων",
        "NEW_MODELS_HEADER": "[b]Νέα Μοντέλα (θα προστεθούν):[/b]",
        "EXISTING_MODELS_DIFF_HEADER": "[b]Υπάρχοντα Μοντέλα με Διαφορετικά Δεδομένα:[/b]",

        # --- Elements / Types / Filters ---
        "NO_ELEMENTS": "Κανένα στοιχείο",
        "NO_ELEMENTS_PAREN": "(Χωρίς στοιχεία)",
        "NO_ELEMENTS_FOR_ITEM": "Δεν υπάρχουν καταχωρημένα στοιχεία για αυτό το στοιχείο.",
        "NO_MODELS": "Δεν υπάρχουν μοντέλα",
        "NO_INACTIVE_ELEMENTS": "Δεν υπάρχουν ανενεργά στοιχεία σε αυτόν τον υποσταθμό",
        # lists used by DBrun
        "ELEMENT_TYPES": [
            "Διακόπτης ΥΤ",
            "Διακόπτης ΜΤ",
            "Μετασχηματιστής 150/20KV",
            "Motor Drive",
            "Μ/Σ Έγχυσης",
            "Μ/Σ Έντασης",
            "Μ/Σ Τάσης",
            "Μ/Σ ΧΤ/ΜΤ (ΒΜΣ)",
            "Αποζεύκτης",
            "Ασφαλειοαποζεύκτης",
            "Γειωτής",
            "Συστοιχία Πυκνωτών",
            "Αντίσταση Κόμβου",
            "Αλεξικέραυνο",
            "Συστοιχία Συσσωρευτών",
        ],
        # Canonical element names used elsewhere in code
        "ELEMENT_BREAKER_YT": "Διακόπτης ΥΤ",
        "ELEMENT_BREAKER_MT": "Διακόπτης ΜΤ",
        "VIDAR_VACUUM_CHECK_LABEL": "ΕΛΕΓΧΟΣ ΚΕΝΟΥ (VIDAR):",
        # VIDAR phase labels and hints
        "VIDAR_LABEL_FA": "ΦΑ-ΦΑ:",
        "VIDAR_LABEL_FB": "ΦΒ-ΦΒ:",
        "VIDAR_LABEL_FC": "ΦΓ-ΦΓ:",
        "VIDAR_HINT": "0.0",
        "VIDAR_SECTION_TITLE": "Έλεγχος Κενού (VIDAR)",
        # Insulation / resistance section titles and labels
        "INSULATION_RESISTANCE_CLOSED_TITLE": "Αντίσταση Μόνωσης - Διακόπτης Κλειστός (Γη)",
        "INSULATION_RESISTANCE_OPEN_TITLE": "Αντίσταση Μόνωσης - Διακόπτης Ανοικτός (Φάση-Φάση)",
        "INSULATION_PASSAGE_TITLE": "Αντίσταση Διέλευσης (μΩ)",
        "INSULATION_MEASUREMENT_CLOSED_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ ΜΟΝΩΣΗΣ - ΔΙΑΚΟΠΤΗΣ ΚΛΕΙΣΤΟΣ (Φ-ΓΗ):",
        "INSULATION_MEASUREMENT_OPEN_HEADER": "ΜΕΤΡΗΣΗ ΑΝΤΙΣΤΑΣΗΣ ΜΟΝΩΣΗΣ - ΔΙΑΚΟΠΤΗΣ ΑΝΟΙΧΤΟΣ (Φ-Φ):",
        "INSULATION_PASSAGE_MEASUREMENT_CLOSED_HEADER": "ΑΝΤΙΣΤΑΣΗ ΔΙΕΛΕΥΣΗΣ (μΩ) - ΔΙΑΚΟΠΤΗΣ ΚΛΕΙΣΤΟΣ:",
        "INSULATION_HINT": "0.0",
        "INSULATION_LABEL_FA_GND": "ΦΑ-Γη",
        "INSULATION_LABEL_FB_GND": "ΦΒ-Γη",
        "INSULATION_LABEL_FC_GND": "ΦΓ-Γη",
        "INSULATION_LABEL_FA": "ΦΑ-ΦΑ",
        "INSULATION_LABEL_FB": "ΦΒ-ΦΒ",
        "INSULATION_LABEL_FC": "ΦΓ-ΦΓ",
        # Generic substring used to detect breaker element types
        "ELEMENT_BREAKER_SUBSTR": "Διακόπτης",
        "BREAKER_CATEGORIES_ALL": ["SF6", "Πτωχού Ελαίου", "Ελαίου", "Κενού"],
        "BREAKER_CATEGORIES_HV": ["SF6", "Ελαίου"],
        "BREAKER_CATEGORIES_MV": ["SF6", "Πτωχού Ελαίου", "Ελαίου", "Κενού"],
        "BREAKER_TYPES": ["Κεντρικός", "Γραμμής", "Διασυνδετικός", "Διακόπτης Πυκνωτών"],
        "OPERATING_STATUS": ["Ενεργή", "Ανενεργή"],
        "INSTALLATION_SPACE": ["Εσωτερικός", "Εξωτερικός"],
        "VOLTAGE_LEVELS": ["(Κενό)", "150/20KV", "20KV", "150KV", "20KV/400V"],
        "VIEW_ELEMENT_TITLE": "Προβολή Στοιχείου",
        "ELEMENTS_LIST_LABEL": "Στοιχεία που συντηρήθηκαν:",
        "PLEASE_SELECT_BREAKER_CATEGORY": "Παρακαλώ επιλέξτε κατηγορία διακόπτη!",
        "PLEASE_SELECT_EML": "Παρακαλώ επιλέξτε αρχείο .eml!",
        "INACTIVE_ELEMENTS": "Ανενεργά Στοιχεία ({count})",
        "ELEMENT_ADDED": "Στοιχείο προστέθηκε στον {substation_name}!",
        "ELEMENT_DUPLICATE": "Υπάρχει ήδη στοιχείο με αυτό το όνομα σε αυτόν τον υποσταθμό!",
        "VIEW_ACTIVE_ELEMENTS": "Εμφάνιση ενεργών στοιχείων ({count})",
        "FILTER_TYPE": "Φίλτρο Τύπου:",
        "FILTER_GATE": "Φίλτρο Πύλης:",
        "FILTER_SUBSTATION": "Φίλτρο Υποσταθμού:",
        "LOC": "Τοποθεσία",
        "ADOPTION": "Ανάληψη",
        "INFO": "Στοιχεία",
        "GATES": "Πύλες",
        "CAPACITORS": "Πυκνωτές",
        "MAINTENANCES": "Συντηρήσεις",
        "LAST": "Τελευταία",
        "SINGLE_LINE": "Μονογραμμικό",
        "MONTHS": [
            "Ιανουάριος",
            "Φεβρουάριος",
            "Μάρτιος",
            "Απρίλιος",
            "Μάιος",
            "Ιούνιος",
            "Ιούλιος",
            "Αύγουστος",
            "Σεπτέμβριος",
            "Οκτώβριος",
            "Νοέμβριος",
            "Δεκέμβριος",
        ],
        "DAYS": [
            "Δευτέρα",
            "Τρίτη",
            "Τετάρτη",
            "Πέμπτη",
            "Παρασκευή",
            "Σάββατο",
            "Κυριακή",
        ],
        # Individual labels / small constants used across the UI
        "BREAKER_LABEL_CENTRAL": "Κεντρικός",
        "BREAKER_LABEL_INTERCON": "Διασυνδετικός",
        "BREAKER_LABEL_CAPACITOR": "Διακόπτης Πυκνωτών",
        "BREAKER_LABEL_LINE": "Γραμμής",
        "GATE_PREFIX": "ΠΥΛΗ",
        "ALL_LABEL": "(Όλα)",
        "DIVISION_DEFAULT": "ΤΜΘ",
        # Additional keys used by the Android UI
        "PICKER_EMPTY_SELECTION": "Ο επιλογέας επέστρεψε κενή επιλογή (None).",
        "ANDROID_FILECHOOSER_FALLBACK": "Ο επιλογέας αρχείων του Android δεν είναι διαθέσιμος. Χρησιμοποίησε τη λίστα αρχείων στο παράθυρο.",
        "FILECHOOSER_NOT_AVAILABLE": "Ο επιλογέας αρχείων δεν είναι διαθέσιμος",
        "FILECHOOSER_ANDROID_ONLY": "Ο επιλογέας αρχείων είναι διαθέσιμος μόνο σε Android.",
        "FILECHOOSER_INTERNAL_ERROR": "Εσωτερικό σφάλμα επιλογέα αρχείων.",
        "FILECHOICE_CANCELLED": "Η επιλογή αρχείου απέτυχε ή ακυρώθηκε.",
        "MODE_LABEL_LOCAL": "Πηγή: Τοπική Βάση",
        "LOCAL_DB_BUTTON": "Τοπική Βάση",
        "CHANGELOG_BUTTON": "Change-log",
        "CHANGELOG_RECORDED": "Η αλλαγή καταγράφηκε στο change log.",
        "ADOPTION_DATE_LABEL": "Ημερομηνία Υιοθέτησης:",
        "NAME_REQUIRED": "Το όνομα είναι υποχρεωτικό",
        "ELEMENT_TYPE_LABEL": "Τύπος Στοιχείου:",
        "RETRY": "Ξαναδοκίμασε",
        "COPYING_FILE": "Αντιγραφή αρχείου...",
        "COPYING_FILE_MSG": "Αντιγραφή αρχείου από το σύστημα αρχείων. Παρακαλώ περιμένετε...",
        "OVERALL_COMMENTS_HINT": "Γενικά σχόλια για την συντήρηση...",
        "GOOGLE_MAPS_LINK": "Google Maps Link",
        "SHARE_BUTTON": "Κοινοποίηση",
        "COPY_PATH": "Αντιγραφή διαδρομής",
        "LOADING_ELEMENTS": "Φόρτωση στοιχείων...",
        "RETRY_LOAD": "Επανάληψη φόρτωσης",
        "ELEM_COMMENTS_HINT": "Σχόλια για αυτό το στοιχείο...",

        # --- UI Actions / Buttons (mirrors BUTTONS when needed) ---
        "SHOW_DB_BUTTON": "Εμφάνιση βάσης υποσταθμών",
        "IMPORT_BUTTON": "Εισαγωγή από αρχείο",
        "MAINTENANCE_BUTTON": "Συντηρήσεις",
        "INSPECTION_BUTTON": "Επιθεωρήσεις",
        "ISOLATION_BUTTON": "Αιτήσεις Απομόνωσης",
        "SF6_BUTTON": "SF6",
        "MODELS_BUTTON": "Διαχείριση Τύπων Στοιχείων",
        "PEOPLE_BUTTON": "Διαχείριση Προσωπικού",
        "TOOLTIP_EDIT": "Επεξεργασία",
        "TOOLTIP_DELETE": "Διαγραφή",
        "TOOLTIP_VIEW": "Προβολή",
        "TOOLTIP_MAINTENANCE": "Συντήρηση",
        "TOOLTIP_INSPECTION": "Επιθεώρηση",
        "VIEW_SHORT": "Εμφ.",
        "PDF_BUTTON": "PDF",

        # --- Prompts / Dialogs / Titles ---
        "VIEW_PROMPT": "Επιλέξτε τι θέλετε να δείτε:",
        "SEARCH_HINT": "Αναζήτηση (όνομα/ημερομηνία)",
        "PREVIOUS": "Προηγούμενη",
        "NEXT": "Επόμενη",
        "LOAD_MORE": "Φόρτωση περισσότερων",
        "PAGE_LABEL_TEMPLATE": "Σελίδα {page}",
        "ALL_SUBSTATIONS_LABEL": "Όλοι οι Υ/Σ",
        "VIEW_SELECTION_TITLE": "Επιλογή Προβολής",
        "SORT_OPTIONS": [
            "Ημερομηνία (φθίνουσα)",
            "Ημερομηνία (αύξουσα)",
            "Υποσταθμός A-Ω",
        ],
        "PAGE_SIZE_LABEL": "Αντικείμενα/σελίδα",
        "PAGE_SIZE_OPTIONS": ["10", "20", "30", "50"],
        "SELECT_PROMPT": "Επιλογή",
        "SHOW_ALL_SUBSTATIONS": "Εμφάνιση Όλων των Υποσταθμών",
        "SELECT_ALL_BTN": "Επιλογή Όλων",
        "ADD_MENU_TITLE": "Προσθήκη υποσταθμών και στοιχείων",
        "ADD_SUBSTATION_BTN": "Προσθήκη Νέου Υποσταθμού",
        "ADD_ELEMENT_BTN": "Προσθήκη Νέου Στοιχείου",
        "ADD_ELEMENTS_TITLE": "Προσθήκη στοιχείων",
        "ADD_SUBSTATION_TITLE": "Προσθήκη Υποσταθμού",
        "ADD_ELEMENT_TITLE": "Προσθήκη Στοιχείου",
        "ADD_MODEL_TITLE": "Προσθήκη Νέου Μοντέλου",
        "ADD_MANUAL": "Προσθήκη Manual",
        "ADD_ELEMENTS_PROMPT": "Προσθέστε στοιχεία για τον νέο υποσταθμό πριν τη συνέχεια:",
        "CONTINUE": "Συνέχεια",
        "OPEN_LOCAL_DB_TITLE": "Άνοιγμα Τοπικής Βάσης",
        "OPEN_FOLDER": "Άνοιγμα φακέλου",
        "CONFIRM_DELETE_TITLE": "Επιβεβαίωση Διαγραφής",
        "DUPLICATE_OPTIONS_INCOMPLETE": (
            "Ολοκληρώστε τις επιλογές για όλα τα διπλότυπα ή χρησιμοποιήστε 'Αντικατάσταση Όλων' / 'Παράλειψη Όλων'."
        ),
        "RESPONSIBLE_NOT_FOUND_TITLE": "Ο υπεύθυνος δε βρέθηκε",

        # --- Misc / Hints ---
        "FORM_NUMBER": "Αρ. Δελτίου:",
        "FORM_NUMBER_HINT": "Αρ. Δελτίου",
        "ELEMENT_NAME_LABEL": "Όνομα Στοιχείου",
        "ELEMENT_NAME_HINT": "Όνομα Στοιχείου",
        "SERIAL_NUMBER_LABEL": "Σειριακός Αριθμός",
        "SERIAL_NUMBER_HINT": "Σειριακός Αριθμός",
        "ELEMENT_MANUFACTURE_YEAR_LABEL": "Έτος κατασκευής",
        "ELEMENT_MANUFACTURE_YEAR_HINT": "YYYY",
        "MAINTENANCE_DATE_LABEL": "Τελευταία Συντ.",
        "MAINTENANCE_DATE_HINT": "YYYY-MM-DD",
        "MANUFACTURER_LABEL": "Κατασκευαστής",
        "MANUFACTURER_HINT": "Κατασκευαστής",
        "MODEL_LABEL": "Μοντέλο",
        "MODEL_HINT": "Μοντέλο",
        "MODEL_VERSION_LABEL": "Έκδοση Μοντέλου",
        "MODEL_VERSION_HINT": "Έκδοση",
        "INSTALLATION_SPACE_LABEL": "Χώρος Εγκατ.",
        "OPERATING_STATUS_LABEL": "Λειτ. Κατάσταση",
        "MAINTENANCE_CYCLE_LABEL": "Κύκλος Συντ.",
        "MAINTENANCE_CYCLE_HINT": "Αριθμός",
        "DATE_LABEL": "Ημερομηνία:",
        "DATE_HINT": "YYYY-MM-DD",
        "REGION_LABEL": "Περιοχή:",
        "REGION_HINT": "Περιοχή",
        "INSPECTOR_LABEL": "Ονομ. Επιθεωρητή:",
        "MONTH_LABEL": "Μήνας:",
        "DAY_LABEL": "Ημέρα:",
        "YEAR_LABEL": "Έτος:",
        "OBSERVATIONS_HINT": "Παρατηρήσεις",

        # --- Email / Reports ---
        "EMAIL_RECIPIENTS_MISSING": (
            "Δεν υπάρχουν παραλήπτες email. Προσθέστε παραλήπτες από τη Διαχείριση Προσωπικού."
        ),
        "MAINTENANCE_HEADER": "Συντήρηση: {name}",
        "PEOPLE_SUMMARY": "Υπεύθυνος: {resp} | Ομάδα: {crew}",
        "COMMENTS_LABEL": "Σχόλια: {text}",
        "MAINTENANCE_COMMENTS_SECTION": "Σχόλια Συντήρησης",
        "ELEMENT_COMMENTS_SECTION": "Σχόλια Στοιχείου",
        "MAINT_LAST_LABEL": "Τελευταία Συντήρηση: {date}",

        # --- Errors & Validation ---
        "INVALID_DATE_FORMAT": "Μη έγκυρη μορφή ημερομηνίας! Χρησιμοποιήστε: YYYY-MM-DD HH:MM",
        "END_BEFORE_START": "Η ημερομηνία λήξης πρέπει να είναι μετά την έναρξη!",
        "ERROR_DURING_CHECK_PREFIX": "Σφάλμα κατά τον έλεγχο: ",
        "RECORD_NOT_FOUND": "Η εγγραφή δεν βρέθηκε.",

        # --- Templates / Import helpers ---
        "TEMPLATE_SUBSTATIONS_TITLE": "Template Υποσταθμών",
        "TEMPLATE_ELEMENTS_TITLE": "Template Στοιχείων",
        "OPENPYXL_MISSING": "openpyxl δεν είναι εγκατεστημένο!",
        "TEMPLATE_SUBSTATIONS_HEADERS": ["Name", "Location", "Adoption Date"],
        "TEMPLATE_ELEMENTS_HEADERS": [
            "Substation Name",
            "Element Type",
            "Name",
            "Serial Number",
            "Maintenance Date",
            "Τύπος Διακόπτη",
            "Breaker Role",
            "Operating Status",
            "Gate",
            "Model Name",
            "Model Manufacturer",
            "Model Installation Space",
        ],

        # --- Other / Deprecated-friendly ---
        "ITEM_DELETED": "Το στοιχείο διαγράφηκε!",
        "MAINTENANCE_UPDATED": "Η συντήρηση ενημερώθηκε!",
        "MAINTENANCE_CREATED": "Η συντήρηση καταχωρήθηκε!",
        "CHANGES_SAVED": "Οι αλλαγές αποθηκεύτηκαν!",
        "CONFIRM_DELETE_SUBSTATION_FMT": "Είστε σίγουροι ότι θέλετε να διαγράψετε\nτον υποσταθμό \"{substation_name}\"\nκαι ΟΛΑ τα στοιχεία του;",
        "CONFIRM_DELETE_MAINT_FMT": "Είστε σίγουροι ότι θέλετε να διαγράψετε\nαυτή τη συντήρηση;",
        "UNREGISTERED_PLACEHOLDER": "(Μη καταχωρημένο)",
        "EMPTY_PLACEHOLDER": "(Κενό)",
        "MODEL_SELECT_PROMPT": "Επιλέξτε μοντέλο",
        "BREAKER_TYPE_LABEL": "Τύπος Διακόπτη:",
        "BREAKER_CATEGORY_LABEL": "Κατηγορία Διακόπτη:",
        "RATED_POWER_HINT": "π.χ. 50",
    },
}
