from typing import Any, Callable

Permission: Any

def check_permission(permission: Any) -> bool: ...
def request_permissions(
    perms: list, callback: Callable[[list, list], None] | None = ...
) -> None: ...
